global proc wf.l_drivenKeys()
{
setAttr l_fingers_anim.curl -10;
setAttr l_fing_index_1_skin.rotateZ 78.32930151;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_index_1_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_index_1_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_index_1_skin.rotateZ -108.5769172;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_index_1_skin.rotateZ -12.63596354;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_index_1_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_index_1_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_index_1_skin.rotateZ 56.45546396;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_index_1_skin.rotateZ -61.73690488;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_index_1_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_index_1_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_index_1_skin.rotateZ -11.01743816;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_1_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_1_skin.rotateZ -18.52534008;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_pointer_anim.curl -10;
setAttr l_fing_index_1_skin.rotateZ 78.32930151;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.curl l_fing_index_1_skin.rotateZ;

setAttr l_pointer_anim.curl 0;
setAttr l_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.curl l_fing_index_1_skin.rotateZ;

setAttr l_pointer_anim.curl 10;
setAttr l_fing_index_1_skin.rotateZ -108.5769172;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.curl l_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateZ;
setAttr l_pointer_anim.curl 0 ;


setAttr l_pointer_anim.scrunch -10;
setAttr l_fing_index_1_skin.rotateZ -12.63596354;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.scrunch l_fing_index_1_skin.rotateZ;

setAttr l_pointer_anim.scrunch 0;
setAttr l_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.scrunch l_fing_index_1_skin.rotateZ;

setAttr l_pointer_anim.scrunch 10;
setAttr l_fing_index_1_skin.rotateZ 56.45546396;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.scrunch l_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateZ;
setAttr l_pointer_anim.scrunch 0 ;


setAttr l_pointer_anim.bend_2 -10000;
setAttr l_fing_index_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.bend_2 l_fing_index_1_skin.rotateZ;

setAttr l_pointer_anim.bend_2 10000;
setAttr l_fing_index_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.bend_2 l_fing_index_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateZ;
setAttr l_pointer_anim.bend_2 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_1_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_1_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.twist -10;
setAttr l_fing_index_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.twist l_fing_index_1_skin.rotateX;

setAttr l_fingers_anim.twist 0;
setAttr l_fing_index_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.twist l_fing_index_1_skin.rotateX;

setAttr l_fingers_anim.twist 10;
setAttr l_fing_index_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.twist l_fing_index_1_skin.rotateX;
selectKey -in 2 -at rotateX l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateX;
setAttr l_fingers_anim.twist 0 ;


setAttr l_pointer_anim.twist -10;
setAttr l_fing_index_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.twist l_fing_index_1_skin.rotateX;

setAttr l_pointer_anim.twist 0;
setAttr l_fing_index_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.twist l_fing_index_1_skin.rotateX;

setAttr l_pointer_anim.twist 10;
setAttr l_fing_index_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.twist l_fing_index_1_skin.rotateX;
selectKey -in 2 -at rotateX l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateX;
setAttr l_pointer_anim.twist 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_1_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_1_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.spread -10;
setAttr l_fing_index_1_skin.rotateY 19.3626902;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_index_1_skin.rotateY;

setAttr l_fingers_anim.spread 0;
setAttr l_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_index_1_skin.rotateY;

setAttr l_fingers_anim.spread 10;
setAttr l_fing_index_1_skin.rotateY -18.2035788;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.spread l_fing_index_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateY;
setAttr l_fingers_anim.spread 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_index_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_index_1_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_index_1_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_index_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_index_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_pointer_anim.spread -10;
setAttr l_fing_index_1_skin.rotateY 19.3626902;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.spread l_fing_index_1_skin.rotateY;

setAttr l_pointer_anim.spread 0;
setAttr l_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.spread l_fing_index_1_skin.rotateY;

setAttr l_pointer_anim.spread 10;
setAttr l_fing_index_1_skin.rotateY -18.2035788;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.spread l_fing_index_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateY;
setAttr l_pointer_anim.spread 0 ;


setAttr l_pointer_anim.lean -10;
setAttr l_fing_index_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.lean l_fing_index_1_skin.rotateY;

setAttr l_pointer_anim.lean 0;
setAttr l_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.lean l_fing_index_1_skin.rotateY;

setAttr l_pointer_anim.lean 10;
setAttr l_fing_index_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.lean l_fing_index_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_1_skin;
setInfinity -poi linear l_fing_index_1_skin.rotateY;
setAttr l_pointer_anim.lean 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_index_2_skin.rotateZ 21.11949021;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_index_2_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_index_2_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_index_2_skin.rotateZ -87.15700325;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_index_2_skin.rotateZ 13.66529213;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_index_2_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_index_2_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_index_2_skin.rotateZ -106.5523827;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_index_2_skin.rotateZ -19.56267814;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_index_2_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_index_2_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_index_2_skin.rotateZ -12.56540926;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_2_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_2_skin.rotateZ -10.12328791;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_pointer_anim.curl -10;
setAttr l_fing_index_2_skin.rotateZ 21.11949021;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.curl l_fing_index_2_skin.rotateZ;

setAttr l_pointer_anim.curl 0;
setAttr l_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.curl l_fing_index_2_skin.rotateZ;

setAttr l_pointer_anim.curl 10;
setAttr l_fing_index_2_skin.rotateZ -87.15700325;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.curl l_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateZ;
setAttr l_pointer_anim.curl 0 ;


setAttr l_pointer_anim.scrunch -10;
setAttr l_fing_index_2_skin.rotateZ 13.66529213;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.scrunch l_fing_index_2_skin.rotateZ;

setAttr l_pointer_anim.scrunch 0;
setAttr l_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.scrunch l_fing_index_2_skin.rotateZ;

setAttr l_pointer_anim.scrunch 10;
setAttr l_fing_index_2_skin.rotateZ -106.5523827;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.scrunch l_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateZ;
setAttr l_pointer_anim.scrunch 0 ;


setAttr l_pointer_anim.bend_3 -10000;
setAttr l_fing_index_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.bend_3 l_fing_index_2_skin.rotateZ;

setAttr l_pointer_anim.bend_3 10000;
setAttr l_fing_index_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.bend_3 l_fing_index_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateZ;
setAttr l_pointer_anim.bend_3 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_2_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_2_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_index_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_index_2_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_index_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_index_2_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_index_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_index_2_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_pointer_anim.lean -10;
setAttr l_fing_index_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.lean l_fing_index_2_skin.rotateY;

setAttr l_pointer_anim.lean 0;
setAttr l_fing_index_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.lean l_fing_index_2_skin.rotateY;

setAttr l_pointer_anim.lean 10;
setAttr l_fing_index_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.lean l_fing_index_2_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateY;
setAttr l_pointer_anim.lean 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_2_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_2_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_index_2_skin;
setInfinity -poi linear l_fing_index_2_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_index_3_skin.rotateZ 9.050007332;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_index_3_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_index_3_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_index_3_skin.rotateZ -85.4661159;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_index_3_skin.rotateZ 11.87313781;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_index_3_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_index_3_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_index_3_skin.rotateZ -65.45889745;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_index_3_skin.rotateZ -12.3313629;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_index_3_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_index_3_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_index_3_skin.rotateZ -10.83629384;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_3_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_3_skin.rotateZ -4.848367826;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_3_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_pointer_anim.curl -10;
setAttr l_fing_index_3_skin.rotateZ 9.050007332;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.curl l_fing_index_3_skin.rotateZ;

setAttr l_pointer_anim.curl 0;
setAttr l_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.curl l_fing_index_3_skin.rotateZ;

setAttr l_pointer_anim.curl 10;
setAttr l_fing_index_3_skin.rotateZ -85.4661159;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.curl l_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateZ;
setAttr l_pointer_anim.curl 0 ;


setAttr l_pointer_anim.scrunch -10;
setAttr l_fing_index_3_skin.rotateZ 11.87313781;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.scrunch l_fing_index_3_skin.rotateZ;

setAttr l_pointer_anim.scrunch 0;
setAttr l_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.scrunch l_fing_index_3_skin.rotateZ;

setAttr l_pointer_anim.scrunch 10;
setAttr l_fing_index_3_skin.rotateZ -65.45889745;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.scrunch l_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateZ;
setAttr l_pointer_anim.scrunch 0 ;


setAttr l_pointer_anim.bend_4 -10000;
setAttr l_fing_index_3_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.bend_4 l_fing_index_3_skin.rotateZ;

setAttr l_pointer_anim.bend_4 10000;
setAttr l_fing_index_3_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.bend_4 l_fing_index_3_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateZ;
setAttr l_pointer_anim.bend_4 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_3_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_3_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_3_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_index_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_index_3_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_index_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_index_3_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_index_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_index_3_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_pointer_anim.lean -10;
setAttr l_fing_index_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.lean l_fing_index_3_skin.rotateY;

setAttr l_pointer_anim.lean 0;
setAttr l_fing_index_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.lean l_fing_index_3_skin.rotateY;

setAttr l_pointer_anim.lean 10;
setAttr l_fing_index_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.lean l_fing_index_3_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateY;
setAttr l_pointer_anim.lean 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_3_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_3_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_3_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_3_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_index_3_skin;
setInfinity -poi linear l_fing_index_3_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_index_base_skin.rotateZ 0.4054526926;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_index_base_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_index_base_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_index_base_skin.rotateZ -2.312425872;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_index_base_skin.rotateZ -5.473259679;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_index_base_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_index_base_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_index_base_skin.rotateZ 7.742912379;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_index_base_skin.rotateZ -10.74539572;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_index_base_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_index_base_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_index_base_skin.rotateZ -5.470478369;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_base_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_base_skin.rotateZ -10.43633574;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_pointer_anim.curl -10;
setAttr l_fing_index_base_skin.rotateZ 0.4054526926;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.curl l_fing_index_base_skin.rotateZ;

setAttr l_pointer_anim.curl 0;
setAttr l_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.curl l_fing_index_base_skin.rotateZ;

setAttr l_pointer_anim.curl 10;
setAttr l_fing_index_base_skin.rotateZ -2.312425872;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.curl l_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateZ;
setAttr l_pointer_anim.curl 0 ;


setAttr l_pointer_anim.scrunch -10;
setAttr l_fing_index_base_skin.rotateZ -5.473259679;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.scrunch l_fing_index_base_skin.rotateZ;

setAttr l_pointer_anim.scrunch 0;
setAttr l_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.scrunch l_fing_index_base_skin.rotateZ;

setAttr l_pointer_anim.scrunch 10;
setAttr l_fing_index_base_skin.rotateZ 7.742912379;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.scrunch l_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateZ;
setAttr l_pointer_anim.scrunch 0 ;


setAttr l_pointer_anim.bend_1 -10000;
setAttr l_fing_index_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.bend_1 l_fing_index_base_skin.rotateZ;

setAttr l_pointer_anim.bend_1 10000;
setAttr l_fing_index_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.bend_1 l_fing_index_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateZ;
setAttr l_pointer_anim.bend_1 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_base_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_base_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.spread -10;
setAttr l_fing_index_base_skin.rotateY 10.74889119;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_index_base_skin.rotateY;

setAttr l_fingers_anim.spread 0;
setAttr l_fing_index_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_index_base_skin.rotateY;

setAttr l_fingers_anim.spread 10;
setAttr l_fing_index_base_skin.rotateY -10.66770307;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.spread l_fing_index_base_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateY;
setAttr l_fingers_anim.spread 0 ;


setAttr l_pointer_anim.spread -10;
setAttr l_fing_index_base_skin.rotateY 10.74889119;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.spread l_fing_index_base_skin.rotateY;

setAttr l_pointer_anim.spread 0;
setAttr l_fing_index_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pointer_anim.spread l_fing_index_base_skin.rotateY;

setAttr l_pointer_anim.spread 10;
setAttr l_fing_index_base_skin.rotateY -10.66770307;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pointer_anim.spread l_fing_index_base_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateY;
setAttr l_pointer_anim.spread 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_index_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_index_base_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_index_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_index_base_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_index_base_skin;
setInfinity -poi linear l_fing_index_base_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_middle_base_skin.rotateZ 0.7178196426;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_middle_base_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_middle_base_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_middle_base_skin.rotateZ -0.03165286661;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_middle_base_skin.rotateZ -6.913657968;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_middle_base_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_middle_base_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_middle_base_skin.rotateZ 6.720692115;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_middle_base_skin.rotateZ -4.386604571;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_middle_base_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_middle_base_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_middle_base_skin.rotateZ -4.641580718;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_base_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_base_skin.rotateZ -2.857250263;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_middle_anim.curl -10;
setAttr l_fing_middle_base_skin.rotateZ 0.7178196426;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.curl l_fing_middle_base_skin.rotateZ;

setAttr l_middle_anim.curl 0;
setAttr l_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.curl l_fing_middle_base_skin.rotateZ;

setAttr l_middle_anim.curl 10;
setAttr l_fing_middle_base_skin.rotateZ -0.03165286661;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.curl l_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateZ;
setAttr l_middle_anim.curl 0 ;


setAttr l_middle_anim.scrunch -10;
setAttr l_fing_middle_base_skin.rotateZ -6.913657968;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.scrunch l_fing_middle_base_skin.rotateZ;

setAttr l_middle_anim.scrunch 0;
setAttr l_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.scrunch l_fing_middle_base_skin.rotateZ;

setAttr l_middle_anim.scrunch 10;
setAttr l_fing_middle_base_skin.rotateZ 6.720692115;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.scrunch l_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateZ;
setAttr l_middle_anim.scrunch 0 ;


setAttr l_middle_anim.bend_1 -10000;
setAttr l_fing_middle_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.bend_1 l_fing_middle_base_skin.rotateZ;

setAttr l_middle_anim.bend_1 10000;
setAttr l_fing_middle_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.bend_1 l_fing_middle_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateZ;
setAttr l_middle_anim.bend_1 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_base_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_base_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.spread 0;
setAttr l_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.spread l_fing_middle_base_skin.rotateY;
selectKey -in 0 -at rotateY l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateY;
setAttr l_fingers_anim.spread 0 ;


setAttr l_fingers_anim.midSpread -10;
setAttr l_fing_middle_base_skin.rotateY -15.28309516;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.midSpread l_fing_middle_base_skin.rotateY;

setAttr l_fingers_anim.midSpread 0;
setAttr l_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.midSpread l_fing_middle_base_skin.rotateY;

setAttr l_fingers_anim.midSpread 10;
setAttr l_fing_middle_base_skin.rotateY 12.70181891;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.midSpread l_fing_middle_base_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateY;
setAttr l_fingers_anim.midSpread 0 ;


setAttr l_middle_anim.spread -10;
setAttr l_fing_middle_base_skin.rotateY -15.28309516;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.spread l_fing_middle_base_skin.rotateY;

setAttr l_middle_anim.spread 0;
setAttr l_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.spread l_fing_middle_base_skin.rotateY;

setAttr l_middle_anim.spread 10;
setAttr l_fing_middle_base_skin.rotateY 12.70181891;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.spread l_fing_middle_base_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateY;
setAttr l_middle_anim.spread 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_base_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_base_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_middle_base_skin;
setInfinity -poi linear l_fing_middle_base_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_base_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_base_skin.rotateY 0.5503159555;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_base_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.spread -10;
setAttr l_fing_pinky_base_skin.rotateY -9.715146913;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_pinky_base_skin.rotateY;

setAttr l_fingers_anim.spread 0;
setAttr l_fing_pinky_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_pinky_base_skin.rotateY;

setAttr l_fingers_anim.spread 10;
setAttr l_fing_pinky_base_skin.rotateY 11.43686341;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.spread l_fing_pinky_base_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateY;
setAttr l_fingers_anim.spread 0 ;


setAttr l_pinky_anim.spread -10;
setAttr l_fing_pinky_base_skin.rotateY -9.715146913;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.spread l_fing_pinky_base_skin.rotateY;

setAttr l_pinky_anim.spread 0;
setAttr l_fing_pinky_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.spread l_fing_pinky_base_skin.rotateY;

setAttr l_pinky_anim.spread 10;
setAttr l_fing_pinky_base_skin.rotateY 11.43686341;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.spread l_fing_pinky_base_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateY;
setAttr l_pinky_anim.spread 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_pinky_base_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_pinky_base_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_pinky_base_skin.rotateZ -3.862950164;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_pinky_base_skin.rotateZ -6.066798462;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_pinky_base_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_pinky_base_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_pinky_base_skin.rotateZ 4.937821436;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_pinky_base_skin.rotateZ -2.013306497;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_pinky_base_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_pinky_base_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_pinky_base_skin.rotateZ -9.008548927;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_base_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_base_skin.rotateZ -21.82017768;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_pinky_anim.curl -10;
setAttr l_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.curl l_fing_pinky_base_skin.rotateZ;

setAttr l_pinky_anim.curl 0;
setAttr l_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.curl l_fing_pinky_base_skin.rotateZ;

setAttr l_pinky_anim.curl 10;
setAttr l_fing_pinky_base_skin.rotateZ -3.862950164;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.curl l_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateZ;
setAttr l_pinky_anim.curl 0 ;


setAttr l_pinky_anim.scrunch -10;
setAttr l_fing_pinky_base_skin.rotateZ -6.066798462;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.scrunch l_fing_pinky_base_skin.rotateZ;

setAttr l_pinky_anim.scrunch 0;
setAttr l_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.scrunch l_fing_pinky_base_skin.rotateZ;

setAttr l_pinky_anim.scrunch 10;
setAttr l_fing_pinky_base_skin.rotateZ 4.937821436;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.scrunch l_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateZ;
setAttr l_pinky_anim.scrunch 0 ;


setAttr l_pinky_anim.bend_1 -10000;
setAttr l_fing_pinky_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.bend_1 l_fing_pinky_base_skin.rotateZ;

setAttr l_pinky_anim.bend_1 10000;
setAttr l_fing_pinky_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.bend_1 l_fing_pinky_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateZ;
setAttr l_pinky_anim.bend_1 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_base_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_base_skin.rotateX -26.17435115;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_base_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_pinky_base_skin;
setInfinity -poi linear l_fing_pinky_base_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_middle_1_skin.rotateZ 84.25943256;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_middle_1_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_middle_1_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_middle_1_skin.rotateZ -100.9601204;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_middle_1_skin.rotateZ -11.05188891;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_middle_1_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_middle_1_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_middle_1_skin.rotateZ 58.08842675;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_middle_1_skin.rotateZ -26.80037002;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_middle_1_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_middle_1_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_middle_1_skin.rotateZ -28.28637612;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_1_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_1_skin.rotateZ -42.43131198;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_middle_anim.curl -10;
setAttr l_fing_middle_1_skin.rotateZ 84.25943256;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.curl l_fing_middle_1_skin.rotateZ;

setAttr l_middle_anim.curl 0;
setAttr l_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.curl l_fing_middle_1_skin.rotateZ;

setAttr l_middle_anim.curl 10;
setAttr l_fing_middle_1_skin.rotateZ -100.9601204;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.curl l_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateZ;
setAttr l_middle_anim.curl 0 ;


setAttr l_middle_anim.scrunch -10;
setAttr l_fing_middle_1_skin.rotateZ -11.05188891;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.scrunch l_fing_middle_1_skin.rotateZ;

setAttr l_middle_anim.scrunch 0;
setAttr l_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.scrunch l_fing_middle_1_skin.rotateZ;

setAttr l_middle_anim.scrunch 10;
setAttr l_fing_middle_1_skin.rotateZ 58.08842675;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.scrunch l_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateZ;
setAttr l_middle_anim.scrunch 0 ;


setAttr l_middle_anim.bend_2 -10000;
setAttr l_fing_middle_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.bend_2 l_fing_middle_1_skin.rotateZ;

setAttr l_middle_anim.bend_2 10000;
setAttr l_fing_middle_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.bend_2 l_fing_middle_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateZ;
setAttr l_middle_anim.bend_2 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_1_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_1_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.twist -10;
setAttr l_fing_middle_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.twist l_fing_middle_1_skin.rotateX;

setAttr l_fingers_anim.twist 0;
setAttr l_fing_middle_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.twist l_fing_middle_1_skin.rotateX;

setAttr l_fingers_anim.twist 10;
setAttr l_fing_middle_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.twist l_fing_middle_1_skin.rotateX;
selectKey -in 2 -at rotateX l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateX;
setAttr l_fingers_anim.twist 0 ;


setAttr l_middle_anim.twist -10;
setAttr l_fing_middle_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.twist l_fing_middle_1_skin.rotateX;

setAttr l_middle_anim.twist 0;
setAttr l_fing_middle_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.twist l_fing_middle_1_skin.rotateX;

setAttr l_middle_anim.twist 10;
setAttr l_fing_middle_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.twist l_fing_middle_1_skin.rotateX;
selectKey -in 2 -at rotateX l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateX;
setAttr l_middle_anim.twist 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_1_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_1_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.spread 0;
setAttr l_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.spread l_fing_middle_1_skin.rotateY;
selectKey -in 0 -at rotateY l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateY;
setAttr l_fingers_anim.spread 0 ;


setAttr l_fingers_anim.midSpread -10;
setAttr l_fing_middle_1_skin.rotateY -26.83512335;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.midSpread l_fing_middle_1_skin.rotateY;

setAttr l_fingers_anim.midSpread 0;
setAttr l_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.midSpread l_fing_middle_1_skin.rotateY;

setAttr l_fingers_anim.midSpread 10;
setAttr l_fing_middle_1_skin.rotateY 27.43479202;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.midSpread l_fing_middle_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateY;
setAttr l_fingers_anim.midSpread 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_middle_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_middle_1_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_middle_1_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_middle_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_middle_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_middle_anim.spread -10;
setAttr l_fing_middle_1_skin.rotateY -26.83512335;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.spread l_fing_middle_1_skin.rotateY;

setAttr l_middle_anim.spread 0;
setAttr l_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.spread l_fing_middle_1_skin.rotateY;

setAttr l_middle_anim.spread 10;
setAttr l_fing_middle_1_skin.rotateY 27.43479202;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.spread l_fing_middle_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateY;
setAttr l_middle_anim.spread 0 ;


setAttr l_middle_anim.lean -10;
setAttr l_fing_middle_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.lean l_fing_middle_1_skin.rotateY;

setAttr l_middle_anim.lean 0;
setAttr l_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.lean l_fing_middle_1_skin.rotateY;

setAttr l_middle_anim.lean 10;
setAttr l_fing_middle_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.lean l_fing_middle_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_1_skin;
setInfinity -poi linear l_fing_middle_1_skin.rotateY;
setAttr l_middle_anim.lean 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_middle_2_skin.rotateZ 15.90899693;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_middle_2_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_middle_2_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_middle_2_skin.rotateZ -92.35253558;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_middle_2_skin.rotateZ 13.80975842;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_middle_2_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_middle_2_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_middle_2_skin.rotateZ -119.5960581;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_middle_2_skin.rotateZ -17.76497131;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_middle_2_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_middle_2_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_middle_2_skin.rotateZ -26.74692067;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_2_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_2_skin.rotateZ -18.07130501;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_middle_anim.curl -10;
setAttr l_fing_middle_2_skin.rotateZ 15.90899693;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.curl l_fing_middle_2_skin.rotateZ;

setAttr l_middle_anim.curl 0;
setAttr l_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.curl l_fing_middle_2_skin.rotateZ;

setAttr l_middle_anim.curl 10;
setAttr l_fing_middle_2_skin.rotateZ -92.35253558;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.curl l_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateZ;
setAttr l_middle_anim.curl 0 ;


setAttr l_middle_anim.scrunch -10;
setAttr l_fing_middle_2_skin.rotateZ 13.80975842;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.scrunch l_fing_middle_2_skin.rotateZ;

setAttr l_middle_anim.scrunch 0;
setAttr l_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.scrunch l_fing_middle_2_skin.rotateZ;

setAttr l_middle_anim.scrunch 10;
setAttr l_fing_middle_2_skin.rotateZ -119.5960581;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.scrunch l_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateZ;
setAttr l_middle_anim.scrunch 0 ;


setAttr l_middle_anim.bend_3 -10000;
setAttr l_fing_middle_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.bend_3 l_fing_middle_2_skin.rotateZ;

setAttr l_middle_anim.bend_3 10000;
setAttr l_fing_middle_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.bend_3 l_fing_middle_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateZ;
setAttr l_middle_anim.bend_3 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_2_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_2_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_middle_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_middle_2_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_middle_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_middle_2_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_middle_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_middle_2_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_middle_anim.lean -10;
setAttr l_fing_middle_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.lean l_fing_middle_2_skin.rotateY;

setAttr l_middle_anim.lean 0;
setAttr l_fing_middle_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.lean l_fing_middle_2_skin.rotateY;

setAttr l_middle_anim.lean 10;
setAttr l_fing_middle_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.lean l_fing_middle_2_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateY;
setAttr l_middle_anim.lean 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_2_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_2_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_middle_2_skin;
setInfinity -poi linear l_fing_middle_2_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_middle_3_skin.rotateZ 8.364632122;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_middle_3_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_middle_3_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_middle_3_skin.rotateZ -108.5301234;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_middle_3_skin.rotateZ 11.88098827;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_middle_3_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_middle_3_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_middle_3_skin.rotateZ -53.51130852;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_middle_3_skin.rotateZ -8.649150338;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_middle_3_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_middle_3_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_middle_3_skin.rotateZ -10.06706695;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_3_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_3_skin.rotateZ -7.361820314;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_3_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_middle_anim.curl -10;
setAttr l_fing_middle_3_skin.rotateZ 8.364632122;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.curl l_fing_middle_3_skin.rotateZ;

setAttr l_middle_anim.curl 0;
setAttr l_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.curl l_fing_middle_3_skin.rotateZ;

setAttr l_middle_anim.curl 10;
setAttr l_fing_middle_3_skin.rotateZ -108.5301234;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.curl l_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateZ;
setAttr l_middle_anim.curl 0 ;


setAttr l_middle_anim.scrunch -10;
setAttr l_fing_middle_3_skin.rotateZ 11.88098827;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.scrunch l_fing_middle_3_skin.rotateZ;

setAttr l_middle_anim.scrunch 0;
setAttr l_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.scrunch l_fing_middle_3_skin.rotateZ;

setAttr l_middle_anim.scrunch 10;
setAttr l_fing_middle_3_skin.rotateZ -53.51130852;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.scrunch l_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateZ;
setAttr l_middle_anim.scrunch 0 ;


setAttr l_middle_anim.bend_4 -10000;
setAttr l_fing_middle_3_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.bend_4 l_fing_middle_3_skin.rotateZ;

setAttr l_middle_anim.bend_4 10000;
setAttr l_fing_middle_3_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.bend_4 l_fing_middle_3_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateZ;
setAttr l_middle_anim.bend_4 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_3_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_3_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_3_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_middle_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_middle_3_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_middle_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_middle_3_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_middle_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_middle_3_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_middle_anim.lean -10;
setAttr l_fing_middle_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.lean l_fing_middle_3_skin.rotateY;

setAttr l_middle_anim.lean 0;
setAttr l_fing_middle_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_middle_anim.lean l_fing_middle_3_skin.rotateY;

setAttr l_middle_anim.lean 10;
setAttr l_fing_middle_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_middle_anim.lean l_fing_middle_3_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateY;
setAttr l_middle_anim.lean 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_middle_3_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_middle_3_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_middle_3_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_middle_3_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_middle_3_skin;
setInfinity -poi linear l_fing_middle_3_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_pinky_1_skin.rotateZ 73.32639952;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_pinky_1_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_pinky_1_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_pinky_1_skin.rotateZ -96.99693582;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_pinky_1_skin.rotateZ -8.83491194;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_pinky_1_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_pinky_1_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_pinky_1_skin.rotateZ 62.38007767;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_pinky_1_skin.rotateZ -12.4269624;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_pinky_1_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_pinky_1_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_pinky_1_skin.rotateZ -54.33575059;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_1_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_1_skin.rotateZ -122.7776808;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_pinky_anim.curl -10;
setAttr l_fing_pinky_1_skin.rotateZ 73.32639952;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.curl l_fing_pinky_1_skin.rotateZ;

setAttr l_pinky_anim.curl 0;
setAttr l_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.curl l_fing_pinky_1_skin.rotateZ;

setAttr l_pinky_anim.curl 10;
setAttr l_fing_pinky_1_skin.rotateZ -96.99693582;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.curl l_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateZ;
setAttr l_pinky_anim.curl 0 ;


setAttr l_pinky_anim.scrunch -10;
setAttr l_fing_pinky_1_skin.rotateZ -8.83491194;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.scrunch l_fing_pinky_1_skin.rotateZ;

setAttr l_pinky_anim.scrunch 0;
setAttr l_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.scrunch l_fing_pinky_1_skin.rotateZ;

setAttr l_pinky_anim.scrunch 10;
setAttr l_fing_pinky_1_skin.rotateZ 62.38007767;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.scrunch l_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateZ;
setAttr l_pinky_anim.scrunch 0 ;


setAttr l_pinky_anim.bend_2 -10000;
setAttr l_fing_pinky_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.bend_2 l_fing_pinky_1_skin.rotateZ;

setAttr l_pinky_anim.bend_2 10000;
setAttr l_fing_pinky_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.bend_2 l_fing_pinky_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateZ;
setAttr l_pinky_anim.bend_2 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_1_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_1_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.twist -10;
setAttr l_fing_pinky_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.twist l_fing_pinky_1_skin.rotateX;

setAttr l_fingers_anim.twist 0;
setAttr l_fing_pinky_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.twist l_fing_pinky_1_skin.rotateX;

setAttr l_fingers_anim.twist 10;
setAttr l_fing_pinky_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.twist l_fing_pinky_1_skin.rotateX;
selectKey -in 2 -at rotateX l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateX;
setAttr l_fingers_anim.twist 0 ;


setAttr l_pinky_anim.twist -10;
setAttr l_fing_pinky_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.twist l_fing_pinky_1_skin.rotateX;

setAttr l_pinky_anim.twist 0;
setAttr l_fing_pinky_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.twist l_fing_pinky_1_skin.rotateX;

setAttr l_pinky_anim.twist 10;
setAttr l_fing_pinky_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.twist l_fing_pinky_1_skin.rotateX;
selectKey -in 2 -at rotateX l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateX;
setAttr l_pinky_anim.twist 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_1_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_1_skin.rotateY 15.63936828;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_1_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.spread -10;
setAttr l_fing_pinky_1_skin.rotateY -25.75286045;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_pinky_1_skin.rotateY;

setAttr l_fingers_anim.spread 0;
setAttr l_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_pinky_1_skin.rotateY;

setAttr l_fingers_anim.spread 10;
setAttr l_fing_pinky_1_skin.rotateY 21.23508417;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.spread l_fing_pinky_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateY;
setAttr l_fingers_anim.spread 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_pinky_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_pinky_1_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_pinky_1_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_pinky_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_pinky_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_pinky_anim.spread -10;
setAttr l_fing_pinky_1_skin.rotateY -25.75286045;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.spread l_fing_pinky_1_skin.rotateY;

setAttr l_pinky_anim.spread 0;
setAttr l_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.spread l_fing_pinky_1_skin.rotateY;

setAttr l_pinky_anim.spread 10;
setAttr l_fing_pinky_1_skin.rotateY 21.23508417;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.spread l_fing_pinky_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateY;
setAttr l_pinky_anim.spread 0 ;


setAttr l_pinky_anim.lean -10;
setAttr l_fing_pinky_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.lean l_fing_pinky_1_skin.rotateY;

setAttr l_pinky_anim.lean 0;
setAttr l_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.lean l_fing_pinky_1_skin.rotateY;

setAttr l_pinky_anim.lean 10;
setAttr l_fing_pinky_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.lean l_fing_pinky_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_1_skin;
setInfinity -poi linear l_fing_pinky_1_skin.rotateY;
setAttr l_pinky_anim.lean 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_pinky_2_skin.rotateZ 18.77672402;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_pinky_2_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_pinky_2_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_pinky_2_skin.rotateZ -86.45621096;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_pinky_2_skin.rotateZ 5.353795415;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_pinky_2_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_pinky_2_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_pinky_2_skin.rotateZ -105.2742772;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_pinky_2_skin.rotateZ -16.04262404;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_pinky_2_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_pinky_2_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_pinky_2_skin.rotateZ -32.77536134;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_2_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_2_skin.rotateZ -6.496048163;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_pinky_anim.curl -10;
setAttr l_fing_pinky_2_skin.rotateZ 18.77672402;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.curl l_fing_pinky_2_skin.rotateZ;

setAttr l_pinky_anim.curl 0;
setAttr l_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.curl l_fing_pinky_2_skin.rotateZ;

setAttr l_pinky_anim.curl 10;
setAttr l_fing_pinky_2_skin.rotateZ -86.45621096;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.curl l_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateZ;
setAttr l_pinky_anim.curl 0 ;


setAttr l_pinky_anim.scrunch -10;
setAttr l_fing_pinky_2_skin.rotateZ 5.353795415;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.scrunch l_fing_pinky_2_skin.rotateZ;

setAttr l_pinky_anim.scrunch 0;
setAttr l_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.scrunch l_fing_pinky_2_skin.rotateZ;

setAttr l_pinky_anim.scrunch 10;
setAttr l_fing_pinky_2_skin.rotateZ -105.2742772;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.scrunch l_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateZ;
setAttr l_pinky_anim.scrunch 0 ;


setAttr l_pinky_anim.bend_3 -10000;
setAttr l_fing_pinky_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.bend_3 l_fing_pinky_2_skin.rotateZ;

setAttr l_pinky_anim.bend_3 10000;
setAttr l_fing_pinky_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.bend_3 l_fing_pinky_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateZ;
setAttr l_pinky_anim.bend_3 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_2_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_2_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_pinky_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_pinky_2_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_pinky_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_pinky_2_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_pinky_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_pinky_2_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_pinky_anim.lean -10;
setAttr l_fing_pinky_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.lean l_fing_pinky_2_skin.rotateY;

setAttr l_pinky_anim.lean 0;
setAttr l_fing_pinky_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.lean l_fing_pinky_2_skin.rotateY;

setAttr l_pinky_anim.lean 10;
setAttr l_fing_pinky_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.lean l_fing_pinky_2_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateY;
setAttr l_pinky_anim.lean 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_2_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_2_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_pinky_2_skin;
setInfinity -poi linear l_fing_pinky_2_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_pinky_3_skin.rotateZ 8.287590435;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_pinky_3_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_pinky_3_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_pinky_3_skin.rotateZ -106.8633359;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_pinky_3_skin.rotateZ 14.72020741;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_pinky_3_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_pinky_3_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_pinky_3_skin.rotateZ -80.8716872;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_pinky_3_skin.rotateZ -7.684617167;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_pinky_3_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_pinky_3_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_pinky_3_skin.rotateZ -17.31530324;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_3_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_3_skin.rotateZ -4.917483508;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_3_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_pinky_anim.curl -10;
setAttr l_fing_pinky_3_skin.rotateZ 8.287590435;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.curl l_fing_pinky_3_skin.rotateZ;

setAttr l_pinky_anim.curl 0;
setAttr l_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.curl l_fing_pinky_3_skin.rotateZ;

setAttr l_pinky_anim.curl 10;
setAttr l_fing_pinky_3_skin.rotateZ -106.8633359;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.curl l_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateZ;
setAttr l_pinky_anim.curl 0 ;


setAttr l_pinky_anim.scrunch -10;
setAttr l_fing_pinky_3_skin.rotateZ 14.72020741;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.scrunch l_fing_pinky_3_skin.rotateZ;

setAttr l_pinky_anim.scrunch 0;
setAttr l_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.scrunch l_fing_pinky_3_skin.rotateZ;

setAttr l_pinky_anim.scrunch 10;
setAttr l_fing_pinky_3_skin.rotateZ -80.8716872;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.scrunch l_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateZ;
setAttr l_pinky_anim.scrunch 0 ;


setAttr l_pinky_anim.bend_4 -10000;
setAttr l_fing_pinky_3_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.bend_4 l_fing_pinky_3_skin.rotateZ;

setAttr l_pinky_anim.bend_4 10000;
setAttr l_fing_pinky_3_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.bend_4 l_fing_pinky_3_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateZ;
setAttr l_pinky_anim.bend_4 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_3_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_3_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_3_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_pinky_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_pinky_3_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_pinky_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_pinky_3_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_pinky_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_pinky_3_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_pinky_anim.lean -10;
setAttr l_fing_pinky_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.lean l_fing_pinky_3_skin.rotateY;

setAttr l_pinky_anim.lean 0;
setAttr l_fing_pinky_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_pinky_anim.lean l_fing_pinky_3_skin.rotateY;

setAttr l_pinky_anim.lean 10;
setAttr l_fing_pinky_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_pinky_anim.lean l_fing_pinky_3_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateY;
setAttr l_pinky_anim.lean 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_pinky_3_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_pinky_3_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_pinky_3_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_pinky_3_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_pinky_3_skin;
setInfinity -poi linear l_fing_pinky_3_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_base_skin.rotateX;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_base_skin.rotateX;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateX;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_base_skin.rotateX;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_base_skin.rotateX;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateX;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_base_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_base_skin.rotateX;
selectKey -in 1 -at rotateX l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbSpread -10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_base_skin.rotateX;

setAttr l_fingers_anim.thumbSpread 0;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_base_skin.rotateX;

setAttr l_fingers_anim.thumbSpread 10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbSpread l_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateX;
setAttr l_fingers_anim.thumbSpread 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_base_skin.rotateX;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_base_skin.rotateX;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateX;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_base_skin.rotateX;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_base_skin.rotateX;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateX;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.orbit -10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_base_skin.rotateX;

setAttr l_thumb_anim.orbit 0;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_base_skin.rotateX;

setAttr l_thumb_anim.orbit 10;
setAttr l_thumb_base_skin.rotateX 7.119336904;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.orbit l_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateX;
setAttr l_thumb_anim.orbit 0 ;


setAttr l_thumb_anim.spread -10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_base_skin.rotateX;

setAttr l_thumb_anim.spread 0;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_base_skin.rotateX;

setAttr l_thumb_anim.spread 10;
setAttr l_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.spread l_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateX;
setAttr l_thumb_anim.spread 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_base_skin.rotateY -2.27336462;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_base_skin.rotateY;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_base_skin.rotateY;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_base_skin.rotateY -0.044043474;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateY;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_base_skin.rotateY;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_base_skin.rotateY;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateY;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_base_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_base_skin.rotateY -3.122295946;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_base_skin.rotateY;
selectKey -in 1 -at rotateY l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbSpread -10;
setAttr l_thumb_base_skin.rotateY 9.558080438;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_base_skin.rotateY;

setAttr l_fingers_anim.thumbSpread 0;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_base_skin.rotateY;

setAttr l_fingers_anim.thumbSpread 10;
setAttr l_thumb_base_skin.rotateY -27.39120145;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbSpread l_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateY;
setAttr l_fingers_anim.thumbSpread 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_base_skin.rotateY -2.27336462;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_base_skin.rotateY;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_base_skin.rotateY;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_base_skin.rotateY -0.044043474;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateY;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_base_skin.rotateY;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_base_skin.rotateY;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateY;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.orbit -10;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_base_skin.rotateY;

setAttr l_thumb_anim.orbit 0;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_base_skin.rotateY;

setAttr l_thumb_anim.orbit 10;
setAttr l_thumb_base_skin.rotateY 20.64770473;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.orbit l_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateY;
setAttr l_thumb_anim.orbit 0 ;


setAttr l_thumb_anim.spread -10;
setAttr l_thumb_base_skin.rotateY 9.558080438;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_base_skin.rotateY;

setAttr l_thumb_anim.spread 0;
setAttr l_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_base_skin.rotateY;

setAttr l_thumb_anim.spread 10;
setAttr l_thumb_base_skin.rotateY -27.39120145;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.spread l_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateY;
setAttr l_thumb_anim.spread 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_base_skin.rotateZ 4.214148983;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_base_skin.rotateZ;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_base_skin.rotateZ;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_base_skin.rotateZ -16.33141023;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateZ;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_base_skin.rotateZ -19.72189891;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_base_skin.rotateZ;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_base_skin.rotateZ;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_base_skin.rotateZ 10.39196858;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateZ;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_base_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_base_skin.rotateZ -64.79671895;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbSpread -10;
setAttr l_thumb_base_skin.rotateZ -5.988039053;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_base_skin.rotateZ;

setAttr l_fingers_anim.thumbSpread 0;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_base_skin.rotateZ;

setAttr l_fingers_anim.thumbSpread 10;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbSpread l_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateZ;
setAttr l_fingers_anim.thumbSpread 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_base_skin.rotateZ 4.214148983;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_base_skin.rotateZ;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_base_skin.rotateZ;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_base_skin.rotateZ -16.33141023;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateZ;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_base_skin.rotateZ -19.72189891;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_base_skin.rotateZ;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_base_skin.rotateZ;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_base_skin.rotateZ 10.39196858;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateZ;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.orbit -10;
setAttr l_thumb_base_skin.rotateZ 22.78146045;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_base_skin.rotateZ;

setAttr l_thumb_anim.orbit 0;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_base_skin.rotateZ;

setAttr l_thumb_anim.orbit 10;
setAttr l_thumb_base_skin.rotateZ -48.57037382;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.orbit l_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateZ;
setAttr l_thumb_anim.orbit 0 ;


setAttr l_thumb_anim.bend_1 -10000;
setAttr l_thumb_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.bend_1 l_thumb_base_skin.rotateZ;

setAttr l_thumb_anim.bend_1 10000;
setAttr l_thumb_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.bend_1 l_thumb_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateZ;
setAttr l_thumb_anim.bend_1 0 ;


setAttr l_thumb_anim.spread -10;
setAttr l_thumb_base_skin.rotateZ -5.988039053;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_base_skin.rotateZ;

setAttr l_thumb_anim.spread 0;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_base_skin.rotateZ;

setAttr l_thumb_anim.spread 10;
setAttr l_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.spread l_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_base_skin;
setInfinity -poi linear l_thumb_base_skin.rotateZ;
setAttr l_thumb_anim.spread 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_twist.rotateX;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_twist.rotateX;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_1_twist.rotateX 22.67841547;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateX;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_twist.rotateX;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_twist.rotateX;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateX;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_1_twist.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_1_twist.rotateX;
selectKey -in 1 -at rotateX l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_twist.rotateX;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_twist.rotateX;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_1_twist.rotateX 22.67841547;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateX;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_twist.rotateX;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_twist.rotateX;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateX;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.orbit -10;
setAttr l_thumb_1_twist.rotateX -14.83081851;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_1_twist.rotateX;

setAttr l_thumb_anim.orbit 0;
setAttr l_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_1_twist.rotateX;

setAttr l_thumb_anim.orbit 10;
setAttr l_thumb_1_twist.rotateX 12.78356059;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.orbit l_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateX;
setAttr l_thumb_anim.orbit 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_twist.rotateY;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_twist.rotateY;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_1_twist.rotateY -6.578744969;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateY;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_twist.rotateY;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_twist.rotateY;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateY;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_1_twist.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_1_twist.rotateY -24.79589275;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_1_twist.rotateY;
selectKey -in 1 -at rotateY l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_twist.rotateY;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_twist.rotateY;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_1_twist.rotateY -6.578744969;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateY;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_twist.rotateY;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_twist.rotateY;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateY;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.orbit -10;
setAttr l_thumb_1_twist.rotateY 6.372233076;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_1_twist.rotateY;

setAttr l_thumb_anim.orbit 0;
setAttr l_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_1_twist.rotateY;

setAttr l_thumb_anim.orbit 10;
setAttr l_thumb_1_twist.rotateY 18.70611263;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.orbit l_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateY;
setAttr l_thumb_anim.orbit 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_twist.rotateZ;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_twist.rotateZ;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_1_twist.rotateZ -2.070467469;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateZ;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_twist.rotateZ;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_twist.rotateZ;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateZ;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_1_twist.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_1_twist.rotateZ;
selectKey -in 1 -at rotateZ l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_twist.rotateZ;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_twist.rotateZ;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_1_twist.rotateZ -2.070467469;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateZ;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_twist.rotateZ;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_twist.rotateZ;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateZ;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.orbit -10;
setAttr l_thumb_1_twist.rotateZ 66.97157776;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_1_twist.rotateZ;

setAttr l_thumb_anim.orbit 0;
setAttr l_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.orbit l_thumb_1_twist.rotateZ;

setAttr l_thumb_anim.orbit 10;
setAttr l_thumb_1_twist.rotateZ -60.04076961;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.orbit l_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_twist;
setInfinity -poi linear l_thumb_1_twist.rotateZ;
setAttr l_thumb_anim.orbit 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_skin.rotateX;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_skin.rotateX;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateX;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_skin.rotateX;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_skin.rotateX;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateX;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_1_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_1_skin.rotateX 14.97313898;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_1_skin.rotateX;
selectKey -in 1 -at rotateX l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbSpread -10;
setAttr l_thumb_1_skin.rotateX 6.181270089;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_1_skin.rotateX;

setAttr l_fingers_anim.thumbSpread 0;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_1_skin.rotateX;

setAttr l_fingers_anim.thumbSpread 10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbSpread l_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateX;
setAttr l_fingers_anim.thumbSpread 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_skin.rotateX;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_skin.rotateX;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateX;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_skin.rotateX;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_skin.rotateX;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateX;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.spread -10;
setAttr l_thumb_1_skin.rotateX 6.181270089;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_1_skin.rotateX;

setAttr l_thumb_anim.spread 0;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_1_skin.rotateX;

setAttr l_thumb_anim.spread 10;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.spread l_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateX;
setAttr l_thumb_anim.spread 0 ;


setAttr l_thumb_anim.twist -10;
setAttr l_thumb_1_skin.rotateX 60;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.twist l_thumb_1_skin.rotateX;

setAttr l_thumb_anim.twist 0;
setAttr l_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.twist l_thumb_1_skin.rotateX;

setAttr l_thumb_anim.twist 10;
setAttr l_thumb_1_skin.rotateX -60;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.twist l_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateX;
setAttr l_thumb_anim.twist 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_skin.rotateY;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_skin.rotateY;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateY;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_skin.rotateY;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_skin.rotateY;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateY;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_1_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_1_skin.rotateY;
selectKey -in 1 -at rotateY l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbSpread -10;
setAttr l_thumb_1_skin.rotateY 53.40587414;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_1_skin.rotateY;

setAttr l_fingers_anim.thumbSpread 0;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_1_skin.rotateY;

setAttr l_fingers_anim.thumbSpread 10;
setAttr l_thumb_1_skin.rotateY -43.65116151;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbSpread l_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateY;
setAttr l_fingers_anim.thumbSpread 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_skin.rotateY;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_skin.rotateY;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateY;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_skin.rotateY;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_skin.rotateY;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateY;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.spread -10;
setAttr l_thumb_1_skin.rotateY 53.40587414;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_1_skin.rotateY;

setAttr l_thumb_anim.spread 0;
setAttr l_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_1_skin.rotateY;

setAttr l_thumb_anim.spread 10;
setAttr l_thumb_1_skin.rotateY -43.65116151;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.spread l_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateY;
setAttr l_thumb_anim.spread 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_1_skin.rotateZ 73.33178069;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_skin.rotateZ;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_1_skin.rotateZ;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_1_skin.rotateZ -69.86465637;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateZ;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_1_skin.rotateZ -10.36760247;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_skin.rotateZ;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_skin.rotateZ;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_1_skin.rotateZ 41.18425035;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateZ;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_1_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_1_skin.rotateZ -99.75624245;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbSpread -10;
setAttr l_thumb_1_skin.rotateZ -10.0196882;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_1_skin.rotateZ;

setAttr l_fingers_anim.thumbSpread 0;
setAttr l_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_1_skin.rotateZ;

setAttr l_fingers_anim.thumbSpread 10;
setAttr l_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbSpread l_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateZ;
setAttr l_fingers_anim.thumbSpread 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_1_skin.rotateZ 73.33178069;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_skin.rotateZ;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_1_skin.rotateZ;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_1_skin.rotateZ -69.86465637;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateZ;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_1_skin.rotateZ -10.36760247;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_skin.rotateZ;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_1_skin.rotateZ;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_1_skin.rotateZ 41.18425035;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateZ;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.bend_2 -10000;
setAttr l_thumb_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.bend_2 l_thumb_1_skin.rotateZ;

setAttr l_thumb_anim.bend_2 10000;
setAttr l_thumb_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.bend_2 l_thumb_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateZ;
setAttr l_thumb_anim.bend_2 0 ;


setAttr l_thumb_anim.spread -10;
setAttr l_thumb_1_skin.rotateZ -10.0196882;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_1_skin.rotateZ;

setAttr l_thumb_anim.spread 0;
setAttr l_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_1_skin.rotateZ;

setAttr l_thumb_anim.spread 10;
setAttr l_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.spread l_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_1_skin;
setInfinity -poi linear l_thumb_1_skin.rotateZ;
setAttr l_thumb_anim.spread 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_2_skin.rotateX;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_2_skin.rotateX;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateX;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_2_skin.rotateX;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_2_skin.rotateX;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateX;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_2_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_2_skin.rotateX;
selectKey -in 1 -at rotateX l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbSpread -10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_2_skin.rotateX;

setAttr l_fingers_anim.thumbSpread 0;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_2_skin.rotateX;

setAttr l_fingers_anim.thumbSpread 10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbSpread l_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateX;
setAttr l_fingers_anim.thumbSpread 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_2_skin.rotateX;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_2_skin.rotateX;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateX;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_2_skin.rotateX;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_2_skin.rotateX;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateX;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.spread -10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_2_skin.rotateX;

setAttr l_thumb_anim.spread 0;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_2_skin.rotateX;

setAttr l_thumb_anim.spread 10;
setAttr l_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.spread l_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateX;
setAttr l_thumb_anim.spread 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_2_skin.rotateY;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_2_skin.rotateY;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateY;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_2_skin.rotateY;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_2_skin.rotateY;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateY;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_2_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_2_skin.rotateY;
selectKey -in 1 -at rotateY l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbSpread -10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_2_skin.rotateY;

setAttr l_fingers_anim.thumbSpread 0;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_2_skin.rotateY;

setAttr l_fingers_anim.thumbSpread 10;
setAttr l_thumb_2_skin.rotateY -0.8200437026;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbSpread l_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateY;
setAttr l_fingers_anim.thumbSpread 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_2_skin.rotateY;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_2_skin.rotateY;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateY;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_2_skin.rotateY;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_2_skin.rotateY;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateY;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.spread -10;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_2_skin.rotateY;

setAttr l_thumb_anim.spread 0;
setAttr l_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_2_skin.rotateY;

setAttr l_thumb_anim.spread 10;
setAttr l_thumb_2_skin.rotateY -0.8200437026;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.spread l_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateY;
setAttr l_thumb_anim.spread 0 ;


setAttr l_fingers_anim.thumbCurl -10;
setAttr l_thumb_2_skin.rotateZ 29.82750794;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_2_skin.rotateZ;

setAttr l_fingers_anim.thumbCurl 0;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbCurl l_thumb_2_skin.rotateZ;

setAttr l_fingers_anim.thumbCurl 10;
setAttr l_thumb_2_skin.rotateZ -62.02574507;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbCurl l_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateZ;
setAttr l_fingers_anim.thumbCurl 0 ;


setAttr l_fingers_anim.thumbScrunch -10;
setAttr l_thumb_2_skin.rotateZ 17.23237314;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_2_skin.rotateZ;

setAttr l_fingers_anim.thumbScrunch 0;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbScrunch l_thumb_2_skin.rotateZ;

setAttr l_fingers_anim.thumbScrunch 10;
setAttr l_thumb_2_skin.rotateZ -125.1179665;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbScrunch l_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateZ;
setAttr l_fingers_anim.thumbScrunch 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_thumb_2_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_thumb_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.thumbSpread -10;
setAttr l_thumb_2_skin.rotateZ -3.604679367;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_2_skin.rotateZ;

setAttr l_fingers_anim.thumbSpread 0;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.thumbSpread l_thumb_2_skin.rotateZ;

setAttr l_fingers_anim.thumbSpread 10;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.thumbSpread l_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateZ;
setAttr l_fingers_anim.thumbSpread 0 ;


setAttr l_thumb_anim.curl -10;
setAttr l_thumb_2_skin.rotateZ 29.82750794;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_2_skin.rotateZ;

setAttr l_thumb_anim.curl 0;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.curl l_thumb_2_skin.rotateZ;

setAttr l_thumb_anim.curl 10;
setAttr l_thumb_2_skin.rotateZ -62.02574507;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.curl l_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateZ;
setAttr l_thumb_anim.curl 0 ;


setAttr l_thumb_anim.scrunch -10;
setAttr l_thumb_2_skin.rotateZ 17.23237314;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_2_skin.rotateZ;

setAttr l_thumb_anim.scrunch 0;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.scrunch l_thumb_2_skin.rotateZ;

setAttr l_thumb_anim.scrunch 10;
setAttr l_thumb_2_skin.rotateZ -125.1179665;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.scrunch l_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateZ;
setAttr l_thumb_anim.scrunch 0 ;


setAttr l_thumb_anim.bend_3 -10000;
setAttr l_thumb_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.bend_3 l_thumb_2_skin.rotateZ;

setAttr l_thumb_anim.bend_3 10000;
setAttr l_thumb_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.bend_3 l_thumb_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateZ;
setAttr l_thumb_anim.bend_3 0 ;


setAttr l_thumb_anim.spread -10;
setAttr l_thumb_2_skin.rotateZ -3.604679367;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_2_skin.rotateZ;

setAttr l_thumb_anim.spread 0;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_thumb_anim.spread l_thumb_2_skin.rotateZ;

setAttr l_thumb_anim.spread 10;
setAttr l_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_thumb_anim.spread l_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_thumb_2_skin;
setInfinity -poi linear l_thumb_2_skin.rotateZ;
setAttr l_thumb_anim.spread 0 ;



if (`objExists l_fing_ring_base_dummy`)
{

setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_base_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_base_skin.rotateY 0.5503159555;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_base_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.spread -10;
setAttr l_fing_ring_base_skin.rotateY -6.715146913;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_ring_base_skin.rotateY;

setAttr l_fingers_anim.spread 0;
setAttr l_fing_ring_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_ring_base_skin.rotateY;

setAttr l_fingers_anim.spread 10;
setAttr l_fing_ring_base_skin.rotateY 6.43686341;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.spread l_fing_ring_base_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateY;
setAttr l_fingers_anim.spread 0 ;


setAttr l_ring_anim.spread -10;
setAttr l_fing_ring_base_skin.rotateY -6.715146913;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.spread l_fing_ring_base_skin.rotateY;

setAttr l_ring_anim.spread 0;
setAttr l_fing_ring_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.spread l_fing_ring_base_skin.rotateY;

setAttr l_ring_anim.spread 10;
setAttr l_fing_ring_base_skin.rotateY 6.43686341;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.spread l_fing_ring_base_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateY;
setAttr l_ring_anim.spread 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_ring_base_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_ring_base_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_ring_base_skin.rotateZ -3.862950164;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_ring_base_skin.rotateZ -6.066798462;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_ring_base_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_ring_base_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_ring_base_skin.rotateZ 4.937821436;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_ring_base_skin.rotateZ -2.013306497;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_ring_base_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_ring_base_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_ring_base_skin.rotateZ -9.008548927;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_base_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_base_skin.rotateZ -21.82017768;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_ring_anim.curl -10;
setAttr l_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.curl l_fing_ring_base_skin.rotateZ;

setAttr l_ring_anim.curl 0;
setAttr l_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.curl l_fing_ring_base_skin.rotateZ;

setAttr l_ring_anim.curl 10;
setAttr l_fing_ring_base_skin.rotateZ -3.862950164;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.curl l_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateZ;
setAttr l_ring_anim.curl 0 ;


setAttr l_ring_anim.scrunch -10;
setAttr l_fing_ring_base_skin.rotateZ -6.066798462;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.scrunch l_fing_ring_base_skin.rotateZ;

setAttr l_ring_anim.scrunch 0;
setAttr l_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.scrunch l_fing_ring_base_skin.rotateZ;

setAttr l_ring_anim.scrunch 10;
setAttr l_fing_ring_base_skin.rotateZ 4.937821436;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.scrunch l_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateZ;
setAttr l_ring_anim.scrunch 0 ;


setAttr l_ring_anim.bend_1 -10000;
setAttr l_fing_ring_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.bend_1 l_fing_ring_base_skin.rotateZ;

setAttr l_ring_anim.bend_1 10000;
setAttr l_fing_ring_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.bend_1 l_fing_ring_base_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateZ;
setAttr l_ring_anim.bend_1 0 ;



setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_base_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_base_skin.rotateX -26.17435115;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_base_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_ring_base_skin;
setInfinity -poi linear l_fing_ring_base_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;




setAttr l_fingers_anim.curl -10;
setAttr l_fing_ring_1_skin.rotateZ 73.32639952;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_ring_1_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_ring_1_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_ring_1_skin.rotateZ -96.99693582;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_ring_1_skin.rotateZ -8.83491194;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_ring_1_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_ring_1_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_ring_1_skin.rotateZ 62.38007767;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_ring_1_skin.rotateZ -12.4269624;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_ring_1_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_ring_1_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_ring_1_skin.rotateZ -54.33575059;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_1_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_1_skin.rotateZ -122.7776808;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_ring_anim.curl -10;
setAttr l_fing_ring_1_skin.rotateZ 73.32639952;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.curl l_fing_ring_1_skin.rotateZ;

setAttr l_ring_anim.curl 0;
setAttr l_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.curl l_fing_ring_1_skin.rotateZ;

setAttr l_ring_anim.curl 10;
setAttr l_fing_ring_1_skin.rotateZ -96.99693582;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.curl l_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateZ;
setAttr l_ring_anim.curl 0 ;


setAttr l_ring_anim.scrunch -10;
setAttr l_fing_ring_1_skin.rotateZ -8.83491194;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.scrunch l_fing_ring_1_skin.rotateZ;

setAttr l_ring_anim.scrunch 0;
setAttr l_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.scrunch l_fing_ring_1_skin.rotateZ;

setAttr l_ring_anim.scrunch 10;
setAttr l_fing_ring_1_skin.rotateZ 62.38007767;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.scrunch l_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateZ;
setAttr l_ring_anim.scrunch 0 ;


setAttr l_ring_anim.bend_2 -10000;
setAttr l_fing_ring_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.bend_2 l_fing_ring_1_skin.rotateZ;

setAttr l_ring_anim.bend_2 10000;
setAttr l_fing_ring_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.bend_2 l_fing_ring_1_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateZ;
setAttr l_ring_anim.bend_2 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_1_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_1_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.twist -10;
setAttr l_fing_ring_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.twist l_fing_ring_1_skin.rotateX;

setAttr l_fingers_anim.twist 0;
setAttr l_fing_ring_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.twist l_fing_ring_1_skin.rotateX;

setAttr l_fingers_anim.twist 10;
setAttr l_fing_ring_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.twist l_fing_ring_1_skin.rotateX;
selectKey -in 2 -at rotateX l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateX;
setAttr l_fingers_anim.twist 0 ;


setAttr l_ring_anim.twist -10;
setAttr l_fing_ring_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.twist l_fing_ring_1_skin.rotateX;

setAttr l_ring_anim.twist 0;
setAttr l_fing_ring_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.twist l_fing_ring_1_skin.rotateX;

setAttr l_ring_anim.twist 10;
setAttr l_fing_ring_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.twist l_fing_ring_1_skin.rotateX;
selectKey -in 2 -at rotateX l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateX;
setAttr l_ring_anim.twist 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_1_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_1_skin.rotateY 15.63936828;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_1_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.spread -10;
setAttr l_fing_ring_1_skin.rotateY -18.75286045;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_ring_1_skin.rotateY;

setAttr l_fingers_anim.spread 0;
setAttr l_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.spread l_fing_ring_1_skin.rotateY;

setAttr l_fingers_anim.spread 10;
setAttr l_fing_ring_1_skin.rotateY 15.23508417;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.spread l_fing_ring_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateY;
setAttr l_fingers_anim.spread 0 ;

setAttr l_fingers_anim.lean -10;
setAttr l_fing_ring_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_ring_1_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_ring_1_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_ring_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_ring_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_ring_anim.spread -10;
setAttr l_fing_ring_1_skin.rotateY -18.75286045;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.spread l_fing_ring_1_skin.rotateY;

setAttr l_ring_anim.spread 0;
setAttr l_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.spread l_fing_ring_1_skin.rotateY;

setAttr l_ring_anim.spread 10;
setAttr l_fing_ring_1_skin.rotateY 15.23508417;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.spread l_fing_ring_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateY;
setAttr l_ring_anim.spread 0 ;


setAttr l_ring_anim.lean -10;
setAttr l_fing_ring_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.lean l_fing_ring_1_skin.rotateY;

setAttr l_ring_anim.lean 0;
setAttr l_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.lean l_fing_ring_1_skin.rotateY;

setAttr l_ring_anim.lean 10;
setAttr l_fing_ring_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.lean l_fing_ring_1_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_1_skin;
setInfinity -poi linear l_fing_ring_1_skin.rotateY;
setAttr l_ring_anim.lean 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_ring_2_skin.rotateZ 18.77672402;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_ring_2_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_ring_2_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_ring_2_skin.rotateZ -86.45621096;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_ring_2_skin.rotateZ 5.353795415;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_ring_2_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_ring_2_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_ring_2_skin.rotateZ -105.2742772;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_ring_2_skin.rotateZ -16.04262404;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_ring_2_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_ring_2_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_ring_2_skin.rotateZ -32.77536134;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_2_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_2_skin.rotateZ -6.496048163;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_ring_anim.curl -10;
setAttr l_fing_ring_2_skin.rotateZ 18.77672402;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.curl l_fing_ring_2_skin.rotateZ;

setAttr l_ring_anim.curl 0;
setAttr l_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.curl l_fing_ring_2_skin.rotateZ;

setAttr l_ring_anim.curl 10;
setAttr l_fing_ring_2_skin.rotateZ -86.45621096;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.curl l_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateZ;
setAttr l_ring_anim.curl 0 ;


setAttr l_ring_anim.scrunch -10;
setAttr l_fing_ring_2_skin.rotateZ 5.353795415;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.scrunch l_fing_ring_2_skin.rotateZ;

setAttr l_ring_anim.scrunch 0;
setAttr l_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.scrunch l_fing_ring_2_skin.rotateZ;

setAttr l_ring_anim.scrunch 10;
setAttr l_fing_ring_2_skin.rotateZ -105.2742772;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.scrunch l_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateZ;
setAttr l_ring_anim.scrunch 0 ;


setAttr l_ring_anim.bend_3 -10000;
setAttr l_fing_ring_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.bend_3 l_fing_ring_2_skin.rotateZ;

setAttr l_ring_anim.bend_3 10000;
setAttr l_fing_ring_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.bend_3 l_fing_ring_2_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateZ;
setAttr l_ring_anim.bend_3 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_2_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_2_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_ring_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_ring_2_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_ring_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_ring_2_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_ring_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_ring_2_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_ring_anim.lean -10;
setAttr l_fing_ring_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.lean l_fing_ring_2_skin.rotateY;

setAttr l_ring_anim.lean 0;
setAttr l_fing_ring_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.lean l_fing_ring_2_skin.rotateY;

setAttr l_ring_anim.lean 10;
setAttr l_fing_ring_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.lean l_fing_ring_2_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateY;
setAttr l_ring_anim.lean 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_2_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_2_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_ring_2_skin;
setInfinity -poi linear l_fing_ring_2_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.curl -10;
setAttr l_fing_ring_3_skin.rotateZ 8.287590435;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_ring_3_skin.rotateZ;

setAttr l_fingers_anim.curl 0;
setAttr l_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.curl l_fing_ring_3_skin.rotateZ;

setAttr l_fingers_anim.curl 10;
setAttr l_fing_ring_3_skin.rotateZ -106.8633359;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.curl l_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateZ;
setAttr l_fingers_anim.curl 0 ;


setAttr l_fingers_anim.scrunch -10;
setAttr l_fing_ring_3_skin.rotateZ 14.72020741;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_ring_3_skin.rotateZ;

setAttr l_fingers_anim.scrunch 0;
setAttr l_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.scrunch l_fing_ring_3_skin.rotateZ;

setAttr l_fingers_anim.scrunch 10;
setAttr l_fing_ring_3_skin.rotateZ -80.8716872;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.scrunch l_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateZ;
setAttr l_fingers_anim.scrunch 0 ;


setAttr l_fingers_anim.relax -10;
setAttr l_fing_ring_3_skin.rotateZ -7.684617167;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_ring_3_skin.rotateZ;

setAttr l_fingers_anim.relax 0;
setAttr l_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.relax l_fing_ring_3_skin.rotateZ;

setAttr l_fingers_anim.relax 10;
setAttr l_fing_ring_3_skin.rotateZ -17.31530324;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.relax l_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateZ;
setAttr l_fingers_anim.relax 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_3_skin.rotateZ;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_3_skin.rotateZ -4.917483508;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_3_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateZ;
setAttr l_fingers_anim.cup 0 ;


setAttr l_ring_anim.curl -10;
setAttr l_fing_ring_3_skin.rotateZ 8.287590435;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.curl l_fing_ring_3_skin.rotateZ;

setAttr l_ring_anim.curl 0;
setAttr l_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.curl l_fing_ring_3_skin.rotateZ;

setAttr l_ring_anim.curl 10;
setAttr l_fing_ring_3_skin.rotateZ -106.8633359;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.curl l_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateZ;
setAttr l_ring_anim.curl 0 ;


setAttr l_ring_anim.scrunch -10;
setAttr l_fing_ring_3_skin.rotateZ 14.72020741;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.scrunch l_fing_ring_3_skin.rotateZ;

setAttr l_ring_anim.scrunch 0;
setAttr l_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.scrunch l_fing_ring_3_skin.rotateZ;

setAttr l_ring_anim.scrunch 10;
setAttr l_fing_ring_3_skin.rotateZ -80.8716872;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.scrunch l_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateZ;
setAttr l_ring_anim.scrunch 0 ;


setAttr l_ring_anim.bend_4 -10000;
setAttr l_fing_ring_3_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.bend_4 l_fing_ring_3_skin.rotateZ;

setAttr l_ring_anim.bend_4 10000;
setAttr l_fing_ring_3_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.bend_4 l_fing_ring_3_skin.rotateZ;
selectKey -in 1 -at rotateZ l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateZ;
setAttr l_ring_anim.bend_4 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_3_skin.rotateY;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_3_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_3_skin.rotateY;
selectKey -in 1 -at rotateY l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateY;
setAttr l_fingers_anim.cup 0 ;


setAttr l_fingers_anim.lean -10;
setAttr l_fing_ring_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_ring_3_skin.rotateY;

setAttr l_fingers_anim.lean 0;
setAttr l_fing_ring_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.lean l_fing_ring_3_skin.rotateY;

setAttr l_fingers_anim.lean 10;
setAttr l_fing_ring_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.lean l_fing_ring_3_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateY;
setAttr l_fingers_anim.lean 0 ;


setAttr l_ring_anim.lean -10;
setAttr l_fing_ring_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.lean l_fing_ring_3_skin.rotateY;

setAttr l_ring_anim.lean 0;
setAttr l_fing_ring_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_ring_anim.lean l_fing_ring_3_skin.rotateY;

setAttr l_ring_anim.lean 10;
setAttr l_fing_ring_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_ring_anim.lean l_fing_ring_3_skin.rotateY;
selectKey -in 2 -at rotateY l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateY;
setAttr l_ring_anim.lean 0 ;


setAttr l_fingers_anim.cup 0;
setAttr l_fing_ring_3_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver l_fingers_anim.cup l_fing_ring_3_skin.rotateX;

setAttr l_fingers_anim.cup 10;
setAttr l_fing_ring_3_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver l_fingers_anim.cup l_fing_ring_3_skin.rotateX;
selectKey -in 1 -at rotateX l_fing_ring_3_skin;
setInfinity -poi linear l_fing_ring_3_skin.rotateX;
setAttr l_fingers_anim.cup 0 ;


select -cl;
selectKey -add -k -f -10 animCurveUA187 ;
selectKey -add -k -f -10 animCurveUA188 ;
selectKey -add -k -f -10 l_fing_ring_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA189 ;
selectKey -add -k -f -10 animCurveUA190 ;
selectKey -add -k -f -10 animCurveUA192 ;
selectKey -add -k -f -10 animCurveUA193 ;
selectKey -add -k -f -10 l_fing_ring_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA195 ;
selectKey -add -k -f -10 animCurveUA196 ;
selectKey -add -k -f -10 animCurveUA198 ;
selectKey -add -k -f -10 animCurveUA199 ;
selectKey -add -k -f -10 animCurveUA201 ;
selectKey -add -k -f -10 animCurveUA202 ;
selectKey -add -k -f -10 animCurveUA203 ;
selectKey -add -k -f -10 animCurveUA204 ;
selectKey -add -k -f -10 animCurveUA205 ;
selectKey -add -k -f -10 animCurveUA206 ;
selectKey -add -k -f -10 l_fing_ring_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA207 ;
selectKey -add -k -f -10 animCurveUA208 ;
selectKey -add -k -f -10 animCurveUA210 ;
selectKey -add -k -f -10 animCurveUA211 ;
selectKey -add -k -f -10 animCurveUA213 ;
selectKey -add -k -f -10 animCurveUA214 ;
selectKey -add -k -f -10 l_fing_ring_3_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA215 ;
selectKey -add -k -f -10 animCurveUA216 ;
selectKey -add -k -f -10 animCurveUA218 ;
selectKey -add -k -f -10 animCurveUA219 ;
selectKey -add -k -f -10 animCurveUA221 ;
selectKey -add -k -f -10 animCurveUA222 ;
keyTangent -itt spline -ott spline;
setInfinity -pri linear;
}




select -r l_hand_base_skin ;
select -hi;
selectKey -clear ;
selectKey -add -k -f 10 l_thumb_base_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA111 ;
selectKey -add -k -f 10 animCurveUA112 ;
selectKey -add -k -f 10 animCurveUA113 ;
selectKey -add -k -f 10 animCurveUA114 ;
selectKey -add -k -f 10 animCurveUA115 ;
selectKey -add -k -f 10 animCurveUA116 ;
selectKey -add -k -f 10 animCurveUA117 ;
selectKey -add -k -f 10 l_thumb_base_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA118 ;
selectKey -add -k -f 10 animCurveUA119 ;
selectKey -add -k -f 10 animCurveUA120 ;
selectKey -add -k -f 10 animCurveUA121 ;
selectKey -add -k -f 10 animCurveUA122 ;
selectKey -add -k -f 10 animCurveUA123 ;
selectKey -add -k -f 10 animCurveUA124 ;
selectKey -add -k -f 10 l_thumb_base_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA125 ;
selectKey -add -k -f 10 animCurveUA126 ;
selectKey -add -k -f 10 animCurveUA127 ;
selectKey -add -k -f 10 animCurveUA128 ;
selectKey -add -k -f 10 animCurveUA129 ;
selectKey -add -k -f 10 animCurveUA130 ;
selectKey -add -k -f 10 animCurveUA132 ;
selectKey -add -k -f 10 l_thumb_1_twist_rotateX ;
selectKey -add -k -f 10 animCurveUA133 ;
selectKey -add -k -f 10 animCurveUA134 ;
selectKey -add -k -f 10 animCurveUA135 ;
selectKey -add -k -f 10 animCurveUA136 ;
selectKey -add -k -f 10 animCurveUA137 ;
selectKey -add -k -f 10 l_thumb_1_twist_rotateY ;
selectKey -add -k -f 10 animCurveUA138 ;
selectKey -add -k -f 10 animCurveUA139 ;
selectKey -add -k -f 10 animCurveUA140 ;
selectKey -add -k -f 10 animCurveUA141 ;
selectKey -add -k -f 10 animCurveUA142 ;
selectKey -add -k -f 10 l_thumb_1_twist_rotateZ ;
selectKey -add -k -f 10 animCurveUA143 ;
selectKey -add -k -f 10 animCurveUA144 ;
selectKey -add -k -f 10 animCurveUA145 ;
selectKey -add -k -f 10 animCurveUA146 ;
selectKey -add -k -f 10 animCurveUA147 ;
selectKey -add -k -f 10 l_thumb_1_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA148 ;
selectKey -add -k -f 10 animCurveUA149 ;
selectKey -add -k -f 10 animCurveUA150 ;
selectKey -add -k -f 10 animCurveUA151 ;
selectKey -add -k -f 10 animCurveUA152 ;
selectKey -add -k -f 10 animCurveUA153 ;
selectKey -add -k -f 10 animCurveUA154 ;
selectKey -add -k -f 10 l_thumb_1_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA155 ;
selectKey -add -k -f 10 animCurveUA156 ;
selectKey -add -k -f 10 animCurveUA157 ;
selectKey -add -k -f 10 animCurveUA158 ;
selectKey -add -k -f 10 animCurveUA159 ;
selectKey -add -k -f 10 animCurveUA160 ;
selectKey -add -k -f 10 l_thumb_1_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA161 ;
selectKey -add -k -f 10 animCurveUA162 ;
selectKey -add -k -f 10 animCurveUA163 ;
selectKey -add -k -f 10 animCurveUA164 ;
selectKey -add -k -f 10 animCurveUA165 ;
selectKey -add -k -f 10 animCurveUA167 ;
selectKey -add -k -f 10 l_thumb_2_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA168 ;
selectKey -add -k -f 10 animCurveUA169 ;
selectKey -add -k -f 10 animCurveUA170 ;
selectKey -add -k -f 10 animCurveUA171 ;
selectKey -add -k -f 10 animCurveUA172 ;
selectKey -add -k -f 10 animCurveUA173 ;
selectKey -add -k -f 10 l_thumb_2_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA174 ;
selectKey -add -k -f 10 animCurveUA175 ;
selectKey -add -k -f 10 animCurveUA176 ;
selectKey -add -k -f 10 animCurveUA177 ;
selectKey -add -k -f 10 animCurveUA178 ;
selectKey -add -k -f 10 animCurveUA179 ;
selectKey -add -k -f 10 l_thumb_2_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA180 ;
selectKey -add -k -f 10 animCurveUA181 ;
selectKey -add -k -f 10 animCurveUA182 ;
selectKey -add -k -f 10 animCurveUA183 ;
selectKey -add -k -f 10 animCurveUA184 ;
selectKey -add -k -f 10 animCurveUA186 ;
selectKey -add -k -f 10 l_fing_index_base_skin_rotateX ;
selectKey -add -k -f 10 l_fing_index_base_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA29 ;
selectKey -add -k -f 10 animCurveUA30 ;
selectKey -add -k -f 10 animCurveUA31 ;
selectKey -add -k -f 10 animCurveUA32 ;
selectKey -add -k -f 10 animCurveUA33 ;
selectKey -add -k -f 10 l_fing_index_base_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA35 ;
selectKey -add -k -f 10 animCurveUA36 ;
selectKey -add -k -f 10 l_fing_index_1_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA1 ;
selectKey -add -k -f 10 animCurveUA2 ;
selectKey -add -k -f 10 animCurveUA3 ;
selectKey -add -k -f 10 animCurveUA4 ;
selectKey -add -k -f 10 animCurveUA5 ;
selectKey -add -k -f 10 l_fing_index_1_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA7 ;
selectKey -add -k -f 10 animCurveUA8 ;
selectKey -add -k -f 10 l_fing_index_1_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA9 ;
selectKey -add -k -f 10 animCurveUA10 ;
selectKey -add -k -f 10 animCurveUA11 ;
selectKey -add -k -f 10 animCurveUA12 ;
selectKey -add -k -f 10 l_fing_index_2_skin_rotateX ;
selectKey -add -k -f 10 l_fing_index_2_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA13 ;
selectKey -add -k -f 10 animCurveUA14 ;
selectKey -add -k -f 10 animCurveUA15 ;
selectKey -add -k -f 10 animCurveUA16 ;
selectKey -add -k -f 10 animCurveUA17 ;
selectKey -add -k -f 10 l_fing_index_2_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA19 ;
selectKey -add -k -f 10 animCurveUA20 ;
selectKey -add -k -f 10 l_fing_index_3_skin_rotateX ;
selectKey -add -k -f 10 l_fing_index_3_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA21 ;
selectKey -add -k -f 10 animCurveUA22 ;
selectKey -add -k -f 10 animCurveUA23 ;
selectKey -add -k -f 10 animCurveUA24 ;
selectKey -add -k -f 10 animCurveUA25 ;
selectKey -add -k -f 10 l_fing_index_3_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA27 ;
selectKey -add -k -f 10 animCurveUA28 ;
selectKey -add -k -f 10 l_fing_middle_base_skin_rotateX ;
selectKey -add -k -f 10 l_fing_middle_base_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA37 ;
selectKey -add -k -f 10 animCurveUA38 ;
selectKey -add -k -f 10 animCurveUA39 ;
selectKey -add -k -f 10 animCurveUA40 ;
selectKey -add -k -f 10 animCurveUA41 ;
selectKey -add -k -f 10 l_fing_middle_base_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA44 ;
selectKey -add -k -f 10 animCurveUA45 ;
selectKey -add -k -f 10 l_fing_middle_1_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA54 ;
selectKey -add -k -f 10 animCurveUA55 ;
selectKey -add -k -f 10 animCurveUA56 ;
selectKey -add -k -f 10 animCurveUA57 ;
selectKey -add -k -f 10 animCurveUA58 ;
selectKey -add -k -f 10 l_fing_middle_1_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA60 ;
selectKey -add -k -f 10 animCurveUA61 ;
selectKey -add -k -f 10 l_fing_middle_1_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA63 ;
selectKey -add -k -f 10 animCurveUA64 ;
selectKey -add -k -f 10 animCurveUA65 ;
selectKey -add -k -f 10 animCurveUA66 ;
selectKey -add -k -f 10 l_fing_middle_2_skin_rotateX ;
selectKey -add -k -f 10 l_fing_middle_2_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA67 ;
selectKey -add -k -f 10 animCurveUA68 ;
selectKey -add -k -f 10 animCurveUA69 ;
selectKey -add -k -f 10 animCurveUA70 ;
selectKey -add -k -f 10 animCurveUA71 ;
selectKey -add -k -f 10 l_fing_middle_2_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA73 ;
selectKey -add -k -f 10 animCurveUA74 ;
selectKey -add -k -f 10 l_fing_middle_3_skin_rotateX ;
selectKey -add -k -f 10 l_fing_middle_3_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA75 ;
selectKey -add -k -f 10 animCurveUA76 ;
selectKey -add -k -f 10 animCurveUA77 ;
selectKey -add -k -f 10 animCurveUA78 ;
selectKey -add -k -f 10 animCurveUA79 ;
selectKey -add -k -f 10 l_fing_middle_3_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA81 ;
selectKey -add -k -f 10 animCurveUA82 ;
selectKey -add -k -f 10 l_fing_pinky_base_skin_rotateX ;
selectKey -add -k -f 10 l_fing_pinky_base_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA46 ;
selectKey -add -k -f 10 animCurveUA47 ;
selectKey -add -k -f 10 l_fing_pinky_base_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA48 ;
selectKey -add -k -f 10 animCurveUA49 ;
selectKey -add -k -f 10 animCurveUA50 ;
selectKey -add -k -f 10 animCurveUA51 ;
selectKey -add -k -f 10 animCurveUA52 ;
selectKey -add -k -f 10 l_fing_pinky_1_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA83 ;
selectKey -add -k -f 10 animCurveUA84 ;
selectKey -add -k -f 10 animCurveUA85 ;
selectKey -add -k -f 10 animCurveUA86 ;
selectKey -add -k -f 10 animCurveUA87 ;
selectKey -add -k -f 10 l_fing_pinky_1_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA89 ;
selectKey -add -k -f 10 animCurveUA90 ;
selectKey -add -k -f 10 l_fing_pinky_1_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA91 ;
selectKey -add -k -f 10 animCurveUA92 ;
selectKey -add -k -f 10 animCurveUA93 ;
selectKey -add -k -f 10 animCurveUA94 ;
selectKey -add -k -f 10 l_fing_pinky_2_skin_rotateX ;
selectKey -add -k -f 10 l_fing_pinky_2_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA95 ;
selectKey -add -k -f 10 animCurveUA96 ;
selectKey -add -k -f 10 animCurveUA97 ;
selectKey -add -k -f 10 animCurveUA98 ;
selectKey -add -k -f 10 animCurveUA99 ;
selectKey -add -k -f 10 l_fing_pinky_2_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA101 ;
selectKey -add -k -f 10 animCurveUA102 ;
selectKey -add -k -f 10 l_fing_pinky_3_skin_rotateX ;
selectKey -add -k -f 10 l_fing_pinky_3_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA103 ;
selectKey -add -k -f 10 animCurveUA104 ;
selectKey -add -k -f 10 animCurveUA105 ;
selectKey -add -k -f 10 animCurveUA106 ;
selectKey -add -k -f 10 animCurveUA107 ;
selectKey -add -k -f 10 l_fing_pinky_3_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA109 ;
selectKey -add -k -f 10 animCurveUA110 ;
setInfinity -poi linear;

selectKey -clear ;
selectKey -add -k -f -10 l_thumb_base_skin_rotateX ;
selectKey -add -k -f -10 animCurveUA111 ;
selectKey -add -k -f -10 animCurveUA113 ;
selectKey -add -k -f -10 animCurveUA114 ;
selectKey -add -k -f -10 animCurveUA115 ;
selectKey -add -k -f -10 animCurveUA116 ;
selectKey -add -k -f -10 animCurveUA117 ;
selectKey -add -k -f -10 l_thumb_base_skin_rotateY ;
selectKey -add -k -f -10 animCurveUA118 ;
selectKey -add -k -f -10 animCurveUA120 ;
selectKey -add -k -f -10 animCurveUA121 ;
selectKey -add -k -f -10 animCurveUA122 ;
selectKey -add -k -f -10 animCurveUA123 ;
selectKey -add -k -f -10 animCurveUA124 ;
selectKey -add -k -f -10 l_thumb_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA125 ;
selectKey -add -k -f -10 animCurveUA127 ;
selectKey -add -k -f -10 animCurveUA128 ;
selectKey -add -k -f -10 animCurveUA129 ;
selectKey -add -k -f -10 animCurveUA130 ;
selectKey -add -k -f -10 animCurveUA132 ;
selectKey -add -k -f -10 l_thumb_1_twist_rotateX ;
selectKey -add -k -f -10 animCurveUA133 ;
selectKey -add -k -f -10 animCurveUA135 ;
selectKey -add -k -f -10 animCurveUA136 ;
selectKey -add -k -f -10 animCurveUA137 ;
selectKey -add -k -f -10 l_thumb_1_twist_rotateY ;
selectKey -add -k -f -10 animCurveUA138 ;
selectKey -add -k -f -10 animCurveUA140 ;
selectKey -add -k -f -10 animCurveUA141 ;
selectKey -add -k -f -10 animCurveUA142 ;
selectKey -add -k -f -10 l_thumb_1_twist_rotateZ ;
selectKey -add -k -f -10 animCurveUA143 ;
selectKey -add -k -f -10 animCurveUA145 ;
selectKey -add -k -f -10 animCurveUA146 ;
selectKey -add -k -f -10 animCurveUA147 ;
selectKey -add -k -f -10 l_thumb_1_skin_rotateX ;
selectKey -add -k -f -10 animCurveUA148 ;
selectKey -add -k -f -10 animCurveUA150 ;
selectKey -add -k -f -10 animCurveUA151 ;
selectKey -add -k -f -10 animCurveUA152 ;
selectKey -add -k -f -10 animCurveUA153 ;
selectKey -add -k -f -10 animCurveUA154 ;
selectKey -add -k -f -10 l_thumb_1_skin_rotateY ;
selectKey -add -k -f -10 animCurveUA155 ;
selectKey -add -k -f -10 animCurveUA157 ;
selectKey -add -k -f -10 animCurveUA158 ;
selectKey -add -k -f -10 animCurveUA159 ;
selectKey -add -k -f -10 animCurveUA160 ;
selectKey -add -k -f -10 l_thumb_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA161 ;
selectKey -add -k -f -10 animCurveUA163 ;
selectKey -add -k -f -10 animCurveUA164 ;
selectKey -add -k -f -10 animCurveUA165 ;
selectKey -add -k -f -10 animCurveUA167 ;
selectKey -add -k -f -10 l_thumb_2_skin_rotateX ;
selectKey -add -k -f -10 animCurveUA168 ;
selectKey -add -k -f -10 animCurveUA170 ;
selectKey -add -k -f -10 animCurveUA171 ;
selectKey -add -k -f -10 animCurveUA172 ;
selectKey -add -k -f -10 animCurveUA173 ;
selectKey -add -k -f -10 l_thumb_2_skin_rotateY ;
selectKey -add -k -f -10 animCurveUA174 ;
selectKey -add -k -f -10 animCurveUA176 ;
selectKey -add -k -f -10 animCurveUA177 ;
selectKey -add -k -f -10 animCurveUA178 ;
selectKey -add -k -f -10 animCurveUA179 ;
selectKey -add -k -f -10 l_thumb_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA180 ;
selectKey -add -k -f -10 animCurveUA182 ;
selectKey -add -k -f -10 animCurveUA183 ;
selectKey -add -k -f -10 animCurveUA184 ;
selectKey -add -k -f -10 animCurveUA186 ;
selectKey -add -k -f -10 l_fing_index_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA29 ;
selectKey -add -k -f -10 animCurveUA30 ;
selectKey -add -k -f -10 animCurveUA32 ;
selectKey -add -k -f -10 animCurveUA33 ;
selectKey -add -k -f -10 animCurveUA35 ;
selectKey -add -k -f -10 animCurveUA36 ;
selectKey -add -k -f -10 l_fing_index_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA1 ;
selectKey -add -k -f -10 animCurveUA2 ;
selectKey -add -k -f -10 animCurveUA4 ;
selectKey -add -k -f -10 animCurveUA5 ;
selectKey -add -k -f -10 animCurveUA7 ;
selectKey -add -k -f -10 animCurveUA8 ;
selectKey -add -k -f -10 animCurveUA9 ;
selectKey -add -k -f -10 animCurveUA10 ;
selectKey -add -k -f -10 animCurveUA11 ;
selectKey -add -k -f -10 animCurveUA12 ;
selectKey -add -k -f -10 l_fing_index_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA13 ;
selectKey -add -k -f -10 animCurveUA14 ;
selectKey -add -k -f -10 animCurveUA16 ;
selectKey -add -k -f -10 animCurveUA17 ;
selectKey -add -k -f -10 animCurveUA19 ;
selectKey -add -k -f -10 animCurveUA20 ;
selectKey -add -k -f -10 l_fing_index_3_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA21 ;
selectKey -add -k -f -10 animCurveUA22 ;
selectKey -add -k -f -10 animCurveUA24 ;
selectKey -add -k -f -10 animCurveUA25 ;
selectKey -add -k -f -10 animCurveUA27 ;
selectKey -add -k -f -10 animCurveUA28 ;
selectKey -add -k -f -10 l_fing_middle_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA37 ;
selectKey -add -k -f -10 animCurveUA38 ;
selectKey -add -k -f -10 animCurveUA40 ;
selectKey -add -k -f -10 animCurveUA41 ;
selectKey -add -k -f -10 animCurveUA44 ;
selectKey -add -k -f -10 animCurveUA45 ;
selectKey -add -k -f -10 l_fing_middle_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA54 ;
selectKey -add -k -f -10 animCurveUA55 ;
selectKey -add -k -f -10 animCurveUA57 ;
selectKey -add -k -f -10 animCurveUA58 ;
selectKey -add -k -f -10 animCurveUA60 ;
selectKey -add -k -f -10 animCurveUA61 ;
selectKey -add -k -f -10 animCurveUA63 ;
selectKey -add -k -f -10 animCurveUA64 ;
selectKey -add -k -f -10 animCurveUA65 ;
selectKey -add -k -f -10 animCurveUA66 ;
selectKey -add -k -f -10 l_fing_middle_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA67 ;
selectKey -add -k -f -10 animCurveUA68 ;
selectKey -add -k -f -10 animCurveUA70 ;
selectKey -add -k -f -10 animCurveUA71 ;
selectKey -add -k -f -10 animCurveUA73 ;
selectKey -add -k -f -10 animCurveUA74 ;
selectKey -add -k -f -10 l_fing_middle_3_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA75 ;
selectKey -add -k -f -10 animCurveUA76 ;
selectKey -add -k -f -10 animCurveUA78 ;
selectKey -add -k -f -10 animCurveUA79 ;
selectKey -add -k -f -10 animCurveUA81 ;
selectKey -add -k -f -10 animCurveUA82 ;
selectKey -add -k -f -10 animCurveUA46 ;
selectKey -add -k -f -10 animCurveUA47 ;
selectKey -add -k -f -10 l_fing_pinky_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA48 ;
selectKey -add -k -f -10 animCurveUA49 ;
selectKey -add -k -f -10 animCurveUA51 ;
selectKey -add -k -f -10 animCurveUA52 ;
selectKey -add -k -f -10 l_fing_pinky_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA83 ;
selectKey -add -k -f -10 animCurveUA84 ;
selectKey -add -k -f -10 animCurveUA86 ;
selectKey -add -k -f -10 animCurveUA87 ;
selectKey -add -k -f -10 animCurveUA89 ;
selectKey -add -k -f -10 animCurveUA90 ;
selectKey -add -k -f -10 animCurveUA91 ;
selectKey -add -k -f -10 animCurveUA92 ;
selectKey -add -k -f -10 animCurveUA93 ;
selectKey -add -k -f -10 animCurveUA94 ;
selectKey -add -k -f -10 l_fing_pinky_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA95 ;
selectKey -add -k -f -10 animCurveUA96 ;
selectKey -add -k -f -10 animCurveUA98 ;
selectKey -add -k -f -10 animCurveUA99 ;
selectKey -add -k -f -10 animCurveUA101 ;
selectKey -add -k -f -10 animCurveUA102 ;
selectKey -add -k -f -10 l_fing_pinky_3_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA103 ;
selectKey -add -k -f -10 animCurveUA104 ;
selectKey -add -k -f -10 animCurveUA106 ;
selectKey -add -k -f -10 animCurveUA107 ;
selectKey -add -k -f -10 animCurveUA109 ;
selectKey -add -k -f -10 animCurveUA110 ;
keyTangent -itt spline -ott spline;
setInfinity -pri linear;

selectKey  -clear;
select -cl;

}