global proc wf.r_drivenKeys()
{
setAttr r_fingers_anim.curl -10;
setAttr r_fing_index_1_skin.rotateZ 78.32930151;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_index_1_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_index_1_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_index_1_skin.rotateZ -108.5769172;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_index_1_skin.rotateZ -12.63596354;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_index_1_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_index_1_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_index_1_skin.rotateZ 56.45546396;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_index_1_skin.rotateZ -61.73690488;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_index_1_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_index_1_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_index_1_skin.rotateZ -11.01743816;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_1_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_1_skin.rotateZ -18.52534008;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_pointer_anim.curl -10;
setAttr r_fing_index_1_skin.rotateZ 78.32930151;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.curl r_fing_index_1_skin.rotateZ;

setAttr r_pointer_anim.curl 0;
setAttr r_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.curl r_fing_index_1_skin.rotateZ;

setAttr r_pointer_anim.curl 10;
setAttr r_fing_index_1_skin.rotateZ -108.5769172;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.curl r_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateZ;
setAttr r_pointer_anim.curl 0 ;


setAttr r_pointer_anim.scrunch -10;
setAttr r_fing_index_1_skin.rotateZ -12.63596354;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.scrunch r_fing_index_1_skin.rotateZ;

setAttr r_pointer_anim.scrunch 0;
setAttr r_fing_index_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.scrunch r_fing_index_1_skin.rotateZ;

setAttr r_pointer_anim.scrunch 10;
setAttr r_fing_index_1_skin.rotateZ 56.45546396;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.scrunch r_fing_index_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateZ;
setAttr r_pointer_anim.scrunch 0 ;


setAttr r_pointer_anim.bend_2 -10000;
setAttr r_fing_index_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.bend_2 r_fing_index_1_skin.rotateZ;

setAttr r_pointer_anim.bend_2 10000;
setAttr r_fing_index_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.bend_2 r_fing_index_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateZ;
setAttr r_pointer_anim.bend_2 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_1_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_1_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.twist -10;
setAttr r_fing_index_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.twist r_fing_index_1_skin.rotateX;

setAttr r_fingers_anim.twist 0;
setAttr r_fing_index_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.twist r_fing_index_1_skin.rotateX;

setAttr r_fingers_anim.twist 10;
setAttr r_fing_index_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.twist r_fing_index_1_skin.rotateX;
selectKey -in 2 -at rotateX r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateX;
setAttr r_fingers_anim.twist 0 ;


setAttr r_pointer_anim.twist -10;
setAttr r_fing_index_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.twist r_fing_index_1_skin.rotateX;

setAttr r_pointer_anim.twist 0;
setAttr r_fing_index_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.twist r_fing_index_1_skin.rotateX;

setAttr r_pointer_anim.twist 10;
setAttr r_fing_index_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.twist r_fing_index_1_skin.rotateX;
selectKey -in 2 -at rotateX r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateX;
setAttr r_pointer_anim.twist 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_1_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_1_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.spread -10;
setAttr r_fing_index_1_skin.rotateY 29.3626902;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_index_1_skin.rotateY;

setAttr r_fingers_anim.spread 0;
setAttr r_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_index_1_skin.rotateY;

setAttr r_fingers_anim.spread 10;
setAttr r_fing_index_1_skin.rotateY -25.2035788;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.spread r_fing_index_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateY;
setAttr r_fingers_anim.spread 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_index_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_index_1_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_index_1_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_index_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_index_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_pointer_anim.spread -10;
setAttr r_fing_index_1_skin.rotateY 19.3626902;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.spread r_fing_index_1_skin.rotateY;

setAttr r_pointer_anim.spread 0;
setAttr r_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.spread r_fing_index_1_skin.rotateY;

setAttr r_pointer_anim.spread 10;
setAttr r_fing_index_1_skin.rotateY -18.2035788;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.spread r_fing_index_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateY;
setAttr r_pointer_anim.spread 0 ;


setAttr r_pointer_anim.lean -10;
setAttr r_fing_index_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.lean r_fing_index_1_skin.rotateY;

setAttr r_pointer_anim.lean 0;
setAttr r_fing_index_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.lean r_fing_index_1_skin.rotateY;

setAttr r_pointer_anim.lean 10;
setAttr r_fing_index_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.lean r_fing_index_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_1_skin;
setInfinity -poi linear r_fing_index_1_skin.rotateY;
setAttr r_pointer_anim.lean 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_index_2_skin.rotateZ 21.11949021;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_index_2_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_index_2_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_index_2_skin.rotateZ -87.15700325;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_index_2_skin.rotateZ 13.66529213;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_index_2_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_index_2_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_index_2_skin.rotateZ -106.5523827;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_index_2_skin.rotateZ -19.56267814;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_index_2_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_index_2_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_index_2_skin.rotateZ -12.56540926;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_2_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_2_skin.rotateZ -10.12328791;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_pointer_anim.curl -10;
setAttr r_fing_index_2_skin.rotateZ 21.11949021;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.curl r_fing_index_2_skin.rotateZ;

setAttr r_pointer_anim.curl 0;
setAttr r_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.curl r_fing_index_2_skin.rotateZ;

setAttr r_pointer_anim.curl 10;
setAttr r_fing_index_2_skin.rotateZ -87.15700325;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.curl r_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateZ;
setAttr r_pointer_anim.curl 0 ;


setAttr r_pointer_anim.scrunch -10;
setAttr r_fing_index_2_skin.rotateZ 13.66529213;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.scrunch r_fing_index_2_skin.rotateZ;

setAttr r_pointer_anim.scrunch 0;
setAttr r_fing_index_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.scrunch r_fing_index_2_skin.rotateZ;

setAttr r_pointer_anim.scrunch 10;
setAttr r_fing_index_2_skin.rotateZ -106.5523827;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.scrunch r_fing_index_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateZ;
setAttr r_pointer_anim.scrunch 0 ;


setAttr r_pointer_anim.bend_3 -10000;
setAttr r_fing_index_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.bend_3 r_fing_index_2_skin.rotateZ;

setAttr r_pointer_anim.bend_3 10000;
setAttr r_fing_index_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.bend_3 r_fing_index_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateZ;
setAttr r_pointer_anim.bend_3 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_2_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_2_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_index_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_index_2_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_index_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_index_2_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_index_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_index_2_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_pointer_anim.lean -10;
setAttr r_fing_index_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.lean r_fing_index_2_skin.rotateY;

setAttr r_pointer_anim.lean 0;
setAttr r_fing_index_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.lean r_fing_index_2_skin.rotateY;

setAttr r_pointer_anim.lean 10;
setAttr r_fing_index_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.lean r_fing_index_2_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateY;
setAttr r_pointer_anim.lean 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_2_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_2_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_index_2_skin;
setInfinity -poi linear r_fing_index_2_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_index_3_skin.rotateZ 9.050007332;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_index_3_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_index_3_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_index_3_skin.rotateZ -85.4661159;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_index_3_skin.rotateZ 11.87313781;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_index_3_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_index_3_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_index_3_skin.rotateZ -65.45889745;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_index_3_skin.rotateZ -12.3313629;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_index_3_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_index_3_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_index_3_skin.rotateZ -10.83629384;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_3_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_3_skin.rotateZ -4.848367826;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_3_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_pointer_anim.curl -10;
setAttr r_fing_index_3_skin.rotateZ 9.050007332;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.curl r_fing_index_3_skin.rotateZ;

setAttr r_pointer_anim.curl 0;
setAttr r_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.curl r_fing_index_3_skin.rotateZ;

setAttr r_pointer_anim.curl 10;
setAttr r_fing_index_3_skin.rotateZ -85.4661159;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.curl r_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateZ;
setAttr r_pointer_anim.curl 0 ;


setAttr r_pointer_anim.scrunch -10;
setAttr r_fing_index_3_skin.rotateZ 11.87313781;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.scrunch r_fing_index_3_skin.rotateZ;

setAttr r_pointer_anim.scrunch 0;
setAttr r_fing_index_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.scrunch r_fing_index_3_skin.rotateZ;

setAttr r_pointer_anim.scrunch 10;
setAttr r_fing_index_3_skin.rotateZ -65.45889745;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.scrunch r_fing_index_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateZ;
setAttr r_pointer_anim.scrunch 0 ;


setAttr r_pointer_anim.bend_4 -10000;
setAttr r_fing_index_3_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.bend_4 r_fing_index_3_skin.rotateZ;

setAttr r_pointer_anim.bend_4 10000;
setAttr r_fing_index_3_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.bend_4 r_fing_index_3_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateZ;
setAttr r_pointer_anim.bend_4 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_3_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_3_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_3_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_index_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_index_3_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_index_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_index_3_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_index_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_index_3_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_pointer_anim.lean -10;
setAttr r_fing_index_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.lean r_fing_index_3_skin.rotateY;

setAttr r_pointer_anim.lean 0;
setAttr r_fing_index_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.lean r_fing_index_3_skin.rotateY;

setAttr r_pointer_anim.lean 10;
setAttr r_fing_index_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.lean r_fing_index_3_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateY;
setAttr r_pointer_anim.lean 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_3_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_3_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_3_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_3_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_index_3_skin;
setInfinity -poi linear r_fing_index_3_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_index_base_skin.rotateZ 0.4054526926;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_index_base_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_index_base_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_index_base_skin.rotateZ -2.312425872;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_index_base_skin.rotateZ -5.473259679;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_index_base_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_index_base_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_index_base_skin.rotateZ 7.742912379;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_index_base_skin.rotateZ -10.74539572;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_index_base_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_index_base_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_index_base_skin.rotateZ -5.470478369;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_base_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_base_skin.rotateZ -10.43633574;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_pointer_anim.curl -10;
setAttr r_fing_index_base_skin.rotateZ 0.4054526926;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.curl r_fing_index_base_skin.rotateZ;

setAttr r_pointer_anim.curl 0;
setAttr r_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.curl r_fing_index_base_skin.rotateZ;

setAttr r_pointer_anim.curl 10;
setAttr r_fing_index_base_skin.rotateZ -2.312425872;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.curl r_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateZ;
setAttr r_pointer_anim.curl 0 ;


setAttr r_pointer_anim.scrunch -10;
setAttr r_fing_index_base_skin.rotateZ -5.473259679;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.scrunch r_fing_index_base_skin.rotateZ;

setAttr r_pointer_anim.scrunch 0;
setAttr r_fing_index_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.scrunch r_fing_index_base_skin.rotateZ;

setAttr r_pointer_anim.scrunch 10;
setAttr r_fing_index_base_skin.rotateZ 7.742912379;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.scrunch r_fing_index_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateZ;
setAttr r_pointer_anim.scrunch 0 ;


setAttr r_pointer_anim.bend_1 -10000;
setAttr r_fing_index_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.bend_1 r_fing_index_base_skin.rotateZ;

setAttr r_pointer_anim.bend_1 10000;
setAttr r_fing_index_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.bend_1 r_fing_index_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateZ;
setAttr r_pointer_anim.bend_1 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_base_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_base_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.spread -10;
setAttr r_fing_index_base_skin.rotateY 10.74889119;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_index_base_skin.rotateY;

setAttr r_fingers_anim.spread 0;
setAttr r_fing_index_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_index_base_skin.rotateY;

setAttr r_fingers_anim.spread 10;
setAttr r_fing_index_base_skin.rotateY -10.66770307;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.spread r_fing_index_base_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateY;
setAttr r_fingers_anim.spread 0 ;


setAttr r_pointer_anim.spread -10;
setAttr r_fing_index_base_skin.rotateY 10.74889119;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.spread r_fing_index_base_skin.rotateY;

setAttr r_pointer_anim.spread 0;
setAttr r_fing_index_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pointer_anim.spread r_fing_index_base_skin.rotateY;

setAttr r_pointer_anim.spread 10;
setAttr r_fing_index_base_skin.rotateY -10.66770307;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pointer_anim.spread r_fing_index_base_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateY;
setAttr r_pointer_anim.spread 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_index_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_index_base_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_index_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_index_base_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_index_base_skin;
setInfinity -poi linear r_fing_index_base_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_middle_base_skin.rotateZ 0.7178196426;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_middle_base_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_middle_base_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_middle_base_skin.rotateZ -0.03165286661;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_middle_base_skin.rotateZ -6.913657968;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_middle_base_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_middle_base_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_middle_base_skin.rotateZ 6.720692115;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_middle_base_skin.rotateZ -4.386604571;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_middle_base_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_middle_base_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_middle_base_skin.rotateZ -4.641580718;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_base_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_base_skin.rotateZ -2.857250263;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_middle_anim.curl -10;
setAttr r_fing_middle_base_skin.rotateZ 0.7178196426;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.curl r_fing_middle_base_skin.rotateZ;

setAttr r_middle_anim.curl 0;
setAttr r_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.curl r_fing_middle_base_skin.rotateZ;

setAttr r_middle_anim.curl 10;
setAttr r_fing_middle_base_skin.rotateZ -0.03165286661;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.curl r_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateZ;
setAttr r_middle_anim.curl 0 ;


setAttr r_middle_anim.scrunch -10;
setAttr r_fing_middle_base_skin.rotateZ -6.913657968;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.scrunch r_fing_middle_base_skin.rotateZ;

setAttr r_middle_anim.scrunch 0;
setAttr r_fing_middle_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.scrunch r_fing_middle_base_skin.rotateZ;

setAttr r_middle_anim.scrunch 10;
setAttr r_fing_middle_base_skin.rotateZ 6.720692115;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.scrunch r_fing_middle_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateZ;
setAttr r_middle_anim.scrunch 0 ;


setAttr r_middle_anim.bend_1 -10000;
setAttr r_fing_middle_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.bend_1 r_fing_middle_base_skin.rotateZ;

setAttr r_middle_anim.bend_1 10000;
setAttr r_fing_middle_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.bend_1 r_fing_middle_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateZ;
setAttr r_middle_anim.bend_1 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_base_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_base_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.spread 0;
setAttr r_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.spread r_fing_middle_base_skin.rotateY;
selectKey -in 0 -at rotateY r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateY;
setAttr r_fingers_anim.spread 0 ;


setAttr r_fingers_anim.midSpread -10;
setAttr r_fing_middle_base_skin.rotateY -15.28309516;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.midSpread r_fing_middle_base_skin.rotateY;

setAttr r_fingers_anim.midSpread 0;
setAttr r_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.midSpread r_fing_middle_base_skin.rotateY;

setAttr r_fingers_anim.midSpread 10;
setAttr r_fing_middle_base_skin.rotateY 12.70181891;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.midSpread r_fing_middle_base_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateY;
setAttr r_fingers_anim.midSpread 0 ;


setAttr r_middle_anim.spread -10;
setAttr r_fing_middle_base_skin.rotateY -15.28309516;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.spread r_fing_middle_base_skin.rotateY;

setAttr r_middle_anim.spread 0;
setAttr r_fing_middle_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.spread r_fing_middle_base_skin.rotateY;

setAttr r_middle_anim.spread 10;
setAttr r_fing_middle_base_skin.rotateY 12.70181891;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.spread r_fing_middle_base_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateY;
setAttr r_middle_anim.spread 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_base_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_base_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_middle_base_skin;
setInfinity -poi linear r_fing_middle_base_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_base_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_base_skin.rotateY 0.5503159555;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_base_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.spread -10;
setAttr r_fing_pinky_base_skin.rotateY -9.715146913;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_pinky_base_skin.rotateY;

setAttr r_fingers_anim.spread 0;
setAttr r_fing_pinky_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_pinky_base_skin.rotateY;

setAttr r_fingers_anim.spread 10;
setAttr r_fing_pinky_base_skin.rotateY 11.43686341;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.spread r_fing_pinky_base_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateY;
setAttr r_fingers_anim.spread 0 ;


setAttr r_pinky_anim.spread -10;
setAttr r_fing_pinky_base_skin.rotateY -9.715146913;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.spread r_fing_pinky_base_skin.rotateY;

setAttr r_pinky_anim.spread 0;
setAttr r_fing_pinky_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.spread r_fing_pinky_base_skin.rotateY;

setAttr r_pinky_anim.spread 10;
setAttr r_fing_pinky_base_skin.rotateY 11.43686341;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.spread r_fing_pinky_base_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateY;
setAttr r_pinky_anim.spread 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_pinky_base_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_pinky_base_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_pinky_base_skin.rotateZ -3.862950164;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_pinky_base_skin.rotateZ -6.066798462;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_pinky_base_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_pinky_base_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_pinky_base_skin.rotateZ 4.937821436;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_pinky_base_skin.rotateZ -2.013306497;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_pinky_base_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_pinky_base_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_pinky_base_skin.rotateZ -9.008548927;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_base_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_base_skin.rotateZ -21.82017768;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_pinky_anim.curl -10;
setAttr r_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.curl r_fing_pinky_base_skin.rotateZ;

setAttr r_pinky_anim.curl 0;
setAttr r_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.curl r_fing_pinky_base_skin.rotateZ;

setAttr r_pinky_anim.curl 10;
setAttr r_fing_pinky_base_skin.rotateZ -3.862950164;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.curl r_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateZ;
setAttr r_pinky_anim.curl 0 ;


setAttr r_pinky_anim.scrunch -10;
setAttr r_fing_pinky_base_skin.rotateZ -6.066798462;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.scrunch r_fing_pinky_base_skin.rotateZ;

setAttr r_pinky_anim.scrunch 0;
setAttr r_fing_pinky_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.scrunch r_fing_pinky_base_skin.rotateZ;

setAttr r_pinky_anim.scrunch 10;
setAttr r_fing_pinky_base_skin.rotateZ 4.937821436;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.scrunch r_fing_pinky_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateZ;
setAttr r_pinky_anim.scrunch 0 ;


setAttr r_pinky_anim.bend_1 -10000;
setAttr r_fing_pinky_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.bend_1 r_fing_pinky_base_skin.rotateZ;

setAttr r_pinky_anim.bend_1 10000;
setAttr r_fing_pinky_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.bend_1 r_fing_pinky_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateZ;
setAttr r_pinky_anim.bend_1 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_base_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_base_skin.rotateX -26.17435115;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_base_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_pinky_base_skin;
setInfinity -poi linear r_fing_pinky_base_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_middle_1_skin.rotateZ 84.25943256;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_middle_1_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_middle_1_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_middle_1_skin.rotateZ -100.9601204;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_middle_1_skin.rotateZ -11.05188891;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_middle_1_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_middle_1_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_middle_1_skin.rotateZ 58.08842675;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_middle_1_skin.rotateZ -26.80037002;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_middle_1_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_middle_1_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_middle_1_skin.rotateZ -28.28637612;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_1_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_1_skin.rotateZ -42.43131198;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_middle_anim.curl -10;
setAttr r_fing_middle_1_skin.rotateZ 84.25943256;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.curl r_fing_middle_1_skin.rotateZ;

setAttr r_middle_anim.curl 0;
setAttr r_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.curl r_fing_middle_1_skin.rotateZ;

setAttr r_middle_anim.curl 10;
setAttr r_fing_middle_1_skin.rotateZ -100.9601204;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.curl r_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateZ;
setAttr r_middle_anim.curl 0 ;


setAttr r_middle_anim.scrunch -10;
setAttr r_fing_middle_1_skin.rotateZ -11.05188891;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.scrunch r_fing_middle_1_skin.rotateZ;

setAttr r_middle_anim.scrunch 0;
setAttr r_fing_middle_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.scrunch r_fing_middle_1_skin.rotateZ;

setAttr r_middle_anim.scrunch 10;
setAttr r_fing_middle_1_skin.rotateZ 58.08842675;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.scrunch r_fing_middle_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateZ;
setAttr r_middle_anim.scrunch 0 ;


setAttr r_middle_anim.bend_2 -10000;
setAttr r_fing_middle_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.bend_2 r_fing_middle_1_skin.rotateZ;

setAttr r_middle_anim.bend_2 10000;
setAttr r_fing_middle_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.bend_2 r_fing_middle_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateZ;
setAttr r_middle_anim.bend_2 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_1_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_1_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.twist -10;
setAttr r_fing_middle_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.twist r_fing_middle_1_skin.rotateX;

setAttr r_fingers_anim.twist 0;
setAttr r_fing_middle_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.twist r_fing_middle_1_skin.rotateX;

setAttr r_fingers_anim.twist 10;
setAttr r_fing_middle_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.twist r_fing_middle_1_skin.rotateX;
selectKey -in 2 -at rotateX r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateX;
setAttr r_fingers_anim.twist 0 ;


setAttr r_middle_anim.twist -10;
setAttr r_fing_middle_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.twist r_fing_middle_1_skin.rotateX;

setAttr r_middle_anim.twist 0;
setAttr r_fing_middle_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.twist r_fing_middle_1_skin.rotateX;

setAttr r_middle_anim.twist 10;
setAttr r_fing_middle_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.twist r_fing_middle_1_skin.rotateX;
selectKey -in 2 -at rotateX r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateX;
setAttr r_middle_anim.twist 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_1_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_1_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.spread 0;
setAttr r_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.spread r_fing_middle_1_skin.rotateY;
selectKey -in 0 -at rotateY r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateY;
setAttr r_fingers_anim.spread 0 ;


setAttr r_fingers_anim.midSpread -10;
setAttr r_fing_middle_1_skin.rotateY -26.83512335;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.midSpread r_fing_middle_1_skin.rotateY;

setAttr r_fingers_anim.midSpread 0;
setAttr r_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.midSpread r_fing_middle_1_skin.rotateY;

setAttr r_fingers_anim.midSpread 10;
setAttr r_fing_middle_1_skin.rotateY 27.43479202;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.midSpread r_fing_middle_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateY;
setAttr r_fingers_anim.midSpread 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_middle_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_middle_1_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_middle_1_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_middle_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_middle_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_middle_anim.spread -10;
setAttr r_fing_middle_1_skin.rotateY -26.83512335;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.spread r_fing_middle_1_skin.rotateY;

setAttr r_middle_anim.spread 0;
setAttr r_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.spread r_fing_middle_1_skin.rotateY;

setAttr r_middle_anim.spread 10;
setAttr r_fing_middle_1_skin.rotateY 27.43479202;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.spread r_fing_middle_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateY;
setAttr r_middle_anim.spread 0 ;


setAttr r_middle_anim.lean -10;
setAttr r_fing_middle_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.lean r_fing_middle_1_skin.rotateY;

setAttr r_middle_anim.lean 0;
setAttr r_fing_middle_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.lean r_fing_middle_1_skin.rotateY;

setAttr r_middle_anim.lean 10;
setAttr r_fing_middle_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.lean r_fing_middle_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_1_skin;
setInfinity -poi linear r_fing_middle_1_skin.rotateY;
setAttr r_middle_anim.lean 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_middle_2_skin.rotateZ 15.90899693;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_middle_2_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_middle_2_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_middle_2_skin.rotateZ -92.35253558;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_middle_2_skin.rotateZ 13.80975842;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_middle_2_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_middle_2_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_middle_2_skin.rotateZ -119.5960581;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_middle_2_skin.rotateZ -17.76497131;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_middle_2_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_middle_2_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_middle_2_skin.rotateZ -26.74692067;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_2_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_2_skin.rotateZ -18.07130501;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_middle_anim.curl -10;
setAttr r_fing_middle_2_skin.rotateZ 15.90899693;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.curl r_fing_middle_2_skin.rotateZ;

setAttr r_middle_anim.curl 0;
setAttr r_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.curl r_fing_middle_2_skin.rotateZ;

setAttr r_middle_anim.curl 10;
setAttr r_fing_middle_2_skin.rotateZ -92.35253558;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.curl r_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateZ;
setAttr r_middle_anim.curl 0 ;


setAttr r_middle_anim.scrunch -10;
setAttr r_fing_middle_2_skin.rotateZ 13.80975842;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.scrunch r_fing_middle_2_skin.rotateZ;

setAttr r_middle_anim.scrunch 0;
setAttr r_fing_middle_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.scrunch r_fing_middle_2_skin.rotateZ;

setAttr r_middle_anim.scrunch 10;
setAttr r_fing_middle_2_skin.rotateZ -119.5960581;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.scrunch r_fing_middle_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateZ;
setAttr r_middle_anim.scrunch 0 ;


setAttr r_middle_anim.bend_3 -10000;
setAttr r_fing_middle_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.bend_3 r_fing_middle_2_skin.rotateZ;

setAttr r_middle_anim.bend_3 10000;
setAttr r_fing_middle_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.bend_3 r_fing_middle_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateZ;
setAttr r_middle_anim.bend_3 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_2_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_2_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_middle_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_middle_2_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_middle_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_middle_2_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_middle_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_middle_2_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_middle_anim.lean -10;
setAttr r_fing_middle_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.lean r_fing_middle_2_skin.rotateY;

setAttr r_middle_anim.lean 0;
setAttr r_fing_middle_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.lean r_fing_middle_2_skin.rotateY;

setAttr r_middle_anim.lean 10;
setAttr r_fing_middle_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.lean r_fing_middle_2_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateY;
setAttr r_middle_anim.lean 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_2_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_2_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_middle_2_skin;
setInfinity -poi linear r_fing_middle_2_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_middle_3_skin.rotateZ 8.364632122;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_middle_3_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_middle_3_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_middle_3_skin.rotateZ -108.5301234;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_middle_3_skin.rotateZ 11.88098827;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_middle_3_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_middle_3_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_middle_3_skin.rotateZ -53.51130852;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_middle_3_skin.rotateZ -8.649150338;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_middle_3_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_middle_3_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_middle_3_skin.rotateZ -10.06706695;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_3_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_3_skin.rotateZ -7.361820314;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_3_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_middle_anim.curl -10;
setAttr r_fing_middle_3_skin.rotateZ 8.364632122;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.curl r_fing_middle_3_skin.rotateZ;

setAttr r_middle_anim.curl 0;
setAttr r_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.curl r_fing_middle_3_skin.rotateZ;

setAttr r_middle_anim.curl 10;
setAttr r_fing_middle_3_skin.rotateZ -108.5301234;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.curl r_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateZ;
setAttr r_middle_anim.curl 0 ;


setAttr r_middle_anim.scrunch -10;
setAttr r_fing_middle_3_skin.rotateZ 11.88098827;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.scrunch r_fing_middle_3_skin.rotateZ;

setAttr r_middle_anim.scrunch 0;
setAttr r_fing_middle_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.scrunch r_fing_middle_3_skin.rotateZ;

setAttr r_middle_anim.scrunch 10;
setAttr r_fing_middle_3_skin.rotateZ -53.51130852;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.scrunch r_fing_middle_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateZ;
setAttr r_middle_anim.scrunch 0 ;


setAttr r_middle_anim.bend_4 -10000;
setAttr r_fing_middle_3_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.bend_4 r_fing_middle_3_skin.rotateZ;

setAttr r_middle_anim.bend_4 10000;
setAttr r_fing_middle_3_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.bend_4 r_fing_middle_3_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateZ;
setAttr r_middle_anim.bend_4 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_3_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_3_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_3_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_middle_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_middle_3_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_middle_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_middle_3_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_middle_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_middle_3_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_middle_anim.lean -10;
setAttr r_fing_middle_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.lean r_fing_middle_3_skin.rotateY;

setAttr r_middle_anim.lean 0;
setAttr r_fing_middle_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_middle_anim.lean r_fing_middle_3_skin.rotateY;

setAttr r_middle_anim.lean 10;
setAttr r_fing_middle_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_middle_anim.lean r_fing_middle_3_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateY;
setAttr r_middle_anim.lean 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_middle_3_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_middle_3_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_middle_3_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_middle_3_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_middle_3_skin;
setInfinity -poi linear r_fing_middle_3_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_pinky_1_skin.rotateZ 73.32639952;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_pinky_1_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_pinky_1_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_pinky_1_skin.rotateZ -96.99693582;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_pinky_1_skin.rotateZ -8.83491194;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_pinky_1_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_pinky_1_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_pinky_1_skin.rotateZ 62.38007767;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_pinky_1_skin.rotateZ -12.4269624;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_pinky_1_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_pinky_1_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_pinky_1_skin.rotateZ -54.33575059;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_1_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_1_skin.rotateZ -122.7776808;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_pinky_anim.curl -10;
setAttr r_fing_pinky_1_skin.rotateZ 73.32639952;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.curl r_fing_pinky_1_skin.rotateZ;

setAttr r_pinky_anim.curl 0;
setAttr r_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.curl r_fing_pinky_1_skin.rotateZ;

setAttr r_pinky_anim.curl 10;
setAttr r_fing_pinky_1_skin.rotateZ -96.99693582;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.curl r_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateZ;
setAttr r_pinky_anim.curl 0 ;


setAttr r_pinky_anim.scrunch -10;
setAttr r_fing_pinky_1_skin.rotateZ -8.83491194;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.scrunch r_fing_pinky_1_skin.rotateZ;

setAttr r_pinky_anim.scrunch 0;
setAttr r_fing_pinky_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.scrunch r_fing_pinky_1_skin.rotateZ;

setAttr r_pinky_anim.scrunch 10;
setAttr r_fing_pinky_1_skin.rotateZ 62.38007767;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.scrunch r_fing_pinky_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateZ;
setAttr r_pinky_anim.scrunch 0 ;


setAttr r_pinky_anim.bend_2 -10000;
setAttr r_fing_pinky_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.bend_2 r_fing_pinky_1_skin.rotateZ;

setAttr r_pinky_anim.bend_2 10000;
setAttr r_fing_pinky_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.bend_2 r_fing_pinky_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateZ;
setAttr r_pinky_anim.bend_2 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_1_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_1_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.twist -10;
setAttr r_fing_pinky_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.twist r_fing_pinky_1_skin.rotateX;

setAttr r_fingers_anim.twist 0;
setAttr r_fing_pinky_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.twist r_fing_pinky_1_skin.rotateX;

setAttr r_fingers_anim.twist 10;
setAttr r_fing_pinky_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.twist r_fing_pinky_1_skin.rotateX;
selectKey -in 2 -at rotateX r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateX;
setAttr r_fingers_anim.twist 0 ;


setAttr r_pinky_anim.twist -10;
setAttr r_fing_pinky_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.twist r_fing_pinky_1_skin.rotateX;

setAttr r_pinky_anim.twist 0;
setAttr r_fing_pinky_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.twist r_fing_pinky_1_skin.rotateX;

setAttr r_pinky_anim.twist 10;
setAttr r_fing_pinky_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.twist r_fing_pinky_1_skin.rotateX;
selectKey -in 2 -at rotateX r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateX;
setAttr r_pinky_anim.twist 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_1_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_1_skin.rotateY 15.63936828;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_1_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.spread -10;
setAttr r_fing_pinky_1_skin.rotateY -25.75286045;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_pinky_1_skin.rotateY;

setAttr r_fingers_anim.spread 0;
setAttr r_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_pinky_1_skin.rotateY;

setAttr r_fingers_anim.spread 10;
setAttr r_fing_pinky_1_skin.rotateY 21.23508417;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.spread r_fing_pinky_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateY;
setAttr r_fingers_anim.spread 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_pinky_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_pinky_1_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_pinky_1_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_pinky_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_pinky_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_pinky_anim.spread -10;
setAttr r_fing_pinky_1_skin.rotateY -25.75286045;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.spread r_fing_pinky_1_skin.rotateY;

setAttr r_pinky_anim.spread 0;
setAttr r_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.spread r_fing_pinky_1_skin.rotateY;

setAttr r_pinky_anim.spread 10;
setAttr r_fing_pinky_1_skin.rotateY 21.23508417;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.spread r_fing_pinky_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateY;
setAttr r_pinky_anim.spread 0 ;


setAttr r_pinky_anim.lean -10;
setAttr r_fing_pinky_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.lean r_fing_pinky_1_skin.rotateY;

setAttr r_pinky_anim.lean 0;
setAttr r_fing_pinky_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.lean r_fing_pinky_1_skin.rotateY;

setAttr r_pinky_anim.lean 10;
setAttr r_fing_pinky_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.lean r_fing_pinky_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_1_skin;
setInfinity -poi linear r_fing_pinky_1_skin.rotateY;
setAttr r_pinky_anim.lean 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_pinky_2_skin.rotateZ 18.77672402;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_pinky_2_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_pinky_2_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_pinky_2_skin.rotateZ -86.45621096;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_pinky_2_skin.rotateZ 5.353795415;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_pinky_2_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_pinky_2_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_pinky_2_skin.rotateZ -105.2742772;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_pinky_2_skin.rotateZ -16.04262404;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_pinky_2_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_pinky_2_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_pinky_2_skin.rotateZ -32.77536134;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_2_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_2_skin.rotateZ -6.496048163;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_pinky_anim.curl -10;
setAttr r_fing_pinky_2_skin.rotateZ 18.77672402;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.curl r_fing_pinky_2_skin.rotateZ;

setAttr r_pinky_anim.curl 0;
setAttr r_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.curl r_fing_pinky_2_skin.rotateZ;

setAttr r_pinky_anim.curl 10;
setAttr r_fing_pinky_2_skin.rotateZ -86.45621096;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.curl r_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateZ;
setAttr r_pinky_anim.curl 0 ;


setAttr r_pinky_anim.scrunch -10;
setAttr r_fing_pinky_2_skin.rotateZ 5.353795415;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.scrunch r_fing_pinky_2_skin.rotateZ;

setAttr r_pinky_anim.scrunch 0;
setAttr r_fing_pinky_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.scrunch r_fing_pinky_2_skin.rotateZ;

setAttr r_pinky_anim.scrunch 10;
setAttr r_fing_pinky_2_skin.rotateZ -105.2742772;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.scrunch r_fing_pinky_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateZ;
setAttr r_pinky_anim.scrunch 0 ;


setAttr r_pinky_anim.bend_3 -10000;
setAttr r_fing_pinky_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.bend_3 r_fing_pinky_2_skin.rotateZ;

setAttr r_pinky_anim.bend_3 10000;
setAttr r_fing_pinky_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.bend_3 r_fing_pinky_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateZ;
setAttr r_pinky_anim.bend_3 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_2_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_2_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_pinky_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_pinky_2_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_pinky_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_pinky_2_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_pinky_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_pinky_2_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_pinky_anim.lean -10;
setAttr r_fing_pinky_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.lean r_fing_pinky_2_skin.rotateY;

setAttr r_pinky_anim.lean 0;
setAttr r_fing_pinky_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.lean r_fing_pinky_2_skin.rotateY;

setAttr r_pinky_anim.lean 10;
setAttr r_fing_pinky_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.lean r_fing_pinky_2_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateY;
setAttr r_pinky_anim.lean 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_2_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_2_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_pinky_2_skin;
setInfinity -poi linear r_fing_pinky_2_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_pinky_3_skin.rotateZ 8.287590435;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_pinky_3_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_pinky_3_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_pinky_3_skin.rotateZ -106.8633359;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_pinky_3_skin.rotateZ 14.72020741;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_pinky_3_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_pinky_3_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_pinky_3_skin.rotateZ -80.8716872;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_pinky_3_skin.rotateZ -7.684617167;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_pinky_3_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_pinky_3_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_pinky_3_skin.rotateZ -17.31530324;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_3_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_3_skin.rotateZ -4.917483508;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_3_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_pinky_anim.curl -10;
setAttr r_fing_pinky_3_skin.rotateZ 8.287590435;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.curl r_fing_pinky_3_skin.rotateZ;

setAttr r_pinky_anim.curl 0;
setAttr r_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.curl r_fing_pinky_3_skin.rotateZ;

setAttr r_pinky_anim.curl 10;
setAttr r_fing_pinky_3_skin.rotateZ -106.8633359;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.curl r_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateZ;
setAttr r_pinky_anim.curl 0 ;


setAttr r_pinky_anim.scrunch -10;
setAttr r_fing_pinky_3_skin.rotateZ 14.72020741;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.scrunch r_fing_pinky_3_skin.rotateZ;

setAttr r_pinky_anim.scrunch 0;
setAttr r_fing_pinky_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.scrunch r_fing_pinky_3_skin.rotateZ;

setAttr r_pinky_anim.scrunch 10;
setAttr r_fing_pinky_3_skin.rotateZ -80.8716872;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.scrunch r_fing_pinky_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateZ;
setAttr r_pinky_anim.scrunch 0 ;


setAttr r_pinky_anim.bend_4 -10000;
setAttr r_fing_pinky_3_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.bend_4 r_fing_pinky_3_skin.rotateZ;

setAttr r_pinky_anim.bend_4 10000;
setAttr r_fing_pinky_3_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.bend_4 r_fing_pinky_3_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateZ;
setAttr r_pinky_anim.bend_4 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_3_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_3_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_3_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_pinky_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_pinky_3_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_pinky_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_pinky_3_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_pinky_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_pinky_3_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_pinky_anim.lean -10;
setAttr r_fing_pinky_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.lean r_fing_pinky_3_skin.rotateY;

setAttr r_pinky_anim.lean 0;
setAttr r_fing_pinky_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_pinky_anim.lean r_fing_pinky_3_skin.rotateY;

setAttr r_pinky_anim.lean 10;
setAttr r_fing_pinky_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_pinky_anim.lean r_fing_pinky_3_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateY;
setAttr r_pinky_anim.lean 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_pinky_3_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_pinky_3_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_pinky_3_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_pinky_3_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_pinky_3_skin;
setInfinity -poi linear r_fing_pinky_3_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_base_skin.rotateX;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_base_skin.rotateX;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateX;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_base_skin.rotateX;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_base_skin.rotateX;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateX;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_base_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_base_skin.rotateX;
selectKey -in 1 -at rotateX r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbSpread -10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_base_skin.rotateX;

setAttr r_fingers_anim.thumbSpread 0;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_base_skin.rotateX;

setAttr r_fingers_anim.thumbSpread 10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbSpread r_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateX;
setAttr r_fingers_anim.thumbSpread 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_base_skin.rotateX;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_base_skin.rotateX;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateX;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_base_skin.rotateX;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_base_skin.rotateX;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateX;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.orbit -10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_base_skin.rotateX;

setAttr r_thumb_anim.orbit 0;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_base_skin.rotateX;

setAttr r_thumb_anim.orbit 10;
setAttr r_thumb_base_skin.rotateX 7.119336904;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.orbit r_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateX;
setAttr r_thumb_anim.orbit 0 ;


setAttr r_thumb_anim.spread -10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_base_skin.rotateX;

setAttr r_thumb_anim.spread 0;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_base_skin.rotateX;

setAttr r_thumb_anim.spread 10;
setAttr r_thumb_base_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.spread r_thumb_base_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateX;
setAttr r_thumb_anim.spread 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_base_skin.rotateY -2.27336462;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_base_skin.rotateY;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_base_skin.rotateY;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_base_skin.rotateY -0.044043474;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateY;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_base_skin.rotateY;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_base_skin.rotateY;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateY;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_base_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_base_skin.rotateY -3.122295946;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_base_skin.rotateY;
selectKey -in 1 -at rotateY r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbSpread -10;
setAttr r_thumb_base_skin.rotateY 9.558080438;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_base_skin.rotateY;

setAttr r_fingers_anim.thumbSpread 0;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_base_skin.rotateY;

setAttr r_fingers_anim.thumbSpread 10;
setAttr r_thumb_base_skin.rotateY -27.39120145;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbSpread r_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateY;
setAttr r_fingers_anim.thumbSpread 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_base_skin.rotateY -2.27336462;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_base_skin.rotateY;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_base_skin.rotateY;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_base_skin.rotateY -0.044043474;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateY;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_base_skin.rotateY;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_base_skin.rotateY;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateY;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.orbit -10;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_base_skin.rotateY;

setAttr r_thumb_anim.orbit 0;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_base_skin.rotateY;

setAttr r_thumb_anim.orbit 10;
setAttr r_thumb_base_skin.rotateY 20.64770473;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.orbit r_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateY;
setAttr r_thumb_anim.orbit 0 ;


setAttr r_thumb_anim.spread -10;
setAttr r_thumb_base_skin.rotateY 9.558080438;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_base_skin.rotateY;

setAttr r_thumb_anim.spread 0;
setAttr r_thumb_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_base_skin.rotateY;

setAttr r_thumb_anim.spread 10;
setAttr r_thumb_base_skin.rotateY -27.39120145;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.spread r_thumb_base_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateY;
setAttr r_thumb_anim.spread 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_base_skin.rotateZ 4.214148983;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_base_skin.rotateZ;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_base_skin.rotateZ;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_base_skin.rotateZ -16.33141023;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateZ;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_base_skin.rotateZ -19.72189891;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_base_skin.rotateZ;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_base_skin.rotateZ;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_base_skin.rotateZ 10.39196858;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateZ;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_base_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_base_skin.rotateZ -64.79671895;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbSpread -10;
setAttr r_thumb_base_skin.rotateZ -5.988039053;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_base_skin.rotateZ;

setAttr r_fingers_anim.thumbSpread 0;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_base_skin.rotateZ;

setAttr r_fingers_anim.thumbSpread 10;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbSpread r_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateZ;
setAttr r_fingers_anim.thumbSpread 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_base_skin.rotateZ 4.214148983;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_base_skin.rotateZ;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_base_skin.rotateZ;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_base_skin.rotateZ -16.33141023;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateZ;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_base_skin.rotateZ -19.72189891;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_base_skin.rotateZ;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_base_skin.rotateZ;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_base_skin.rotateZ 10.39196858;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateZ;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.orbit -10;
setAttr r_thumb_base_skin.rotateZ 22.78146045;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_base_skin.rotateZ;

setAttr r_thumb_anim.orbit 0;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_base_skin.rotateZ;

setAttr r_thumb_anim.orbit 10;
setAttr r_thumb_base_skin.rotateZ -48.57037382;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.orbit r_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateZ;
setAttr r_thumb_anim.orbit 0 ;


setAttr r_thumb_anim.bend_1 -10000;
setAttr r_thumb_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.bend_1 r_thumb_base_skin.rotateZ;

setAttr r_thumb_anim.bend_1 10000;
setAttr r_thumb_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.bend_1 r_thumb_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateZ;
setAttr r_thumb_anim.bend_1 0 ;


setAttr r_thumb_anim.spread -10;
setAttr r_thumb_base_skin.rotateZ -5.988039053;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_base_skin.rotateZ;

setAttr r_thumb_anim.spread 0;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_base_skin.rotateZ;

setAttr r_thumb_anim.spread 10;
setAttr r_thumb_base_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.spread r_thumb_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_base_skin;
setInfinity -poi linear r_thumb_base_skin.rotateZ;
setAttr r_thumb_anim.spread 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_twist.rotateX;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_twist.rotateX;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_1_twist.rotateX 22.67841547;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateX;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_twist.rotateX;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_twist.rotateX;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateX;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_1_twist.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_1_twist.rotateX;
selectKey -in 1 -at rotateX r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_twist.rotateX;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_twist.rotateX;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_1_twist.rotateX 22.67841547;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateX;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_twist.rotateX;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_twist.rotateX;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateX;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.orbit -10;
setAttr r_thumb_1_twist.rotateX -14.83081851;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_1_twist.rotateX;

setAttr r_thumb_anim.orbit 0;
setAttr r_thumb_1_twist.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_1_twist.rotateX;

setAttr r_thumb_anim.orbit 10;
setAttr r_thumb_1_twist.rotateX 12.78356059;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.orbit r_thumb_1_twist.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateX;
setAttr r_thumb_anim.orbit 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_twist.rotateY;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_twist.rotateY;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_1_twist.rotateY -6.578744969;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateY;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_twist.rotateY;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_twist.rotateY;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateY;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_1_twist.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_1_twist.rotateY -24.79589275;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_1_twist.rotateY;
selectKey -in 1 -at rotateY r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_twist.rotateY;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_twist.rotateY;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_1_twist.rotateY -6.578744969;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateY;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_twist.rotateY;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_twist.rotateY;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateY;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.orbit -10;
setAttr r_thumb_1_twist.rotateY 6.372233076;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_1_twist.rotateY;

setAttr r_thumb_anim.orbit 0;
setAttr r_thumb_1_twist.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_1_twist.rotateY;

setAttr r_thumb_anim.orbit 10;
setAttr r_thumb_1_twist.rotateY 18.70611263;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.orbit r_thumb_1_twist.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateY;
setAttr r_thumb_anim.orbit 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_twist.rotateZ;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_twist.rotateZ;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_1_twist.rotateZ -2.070467469;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateZ;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_twist.rotateZ;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_twist.rotateZ;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateZ;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_1_twist.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_1_twist.rotateZ;
selectKey -in 1 -at rotateZ r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_twist.rotateZ;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_twist.rotateZ;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_1_twist.rotateZ -2.070467469;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateZ;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_twist.rotateZ;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_twist.rotateZ;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateZ;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.orbit -10;
setAttr r_thumb_1_twist.rotateZ 66.97157776;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_1_twist.rotateZ;

setAttr r_thumb_anim.orbit 0;
setAttr r_thumb_1_twist.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.orbit r_thumb_1_twist.rotateZ;

setAttr r_thumb_anim.orbit 10;
setAttr r_thumb_1_twist.rotateZ -60.04076961;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.orbit r_thumb_1_twist.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_twist;
setInfinity -poi linear r_thumb_1_twist.rotateZ;
setAttr r_thumb_anim.orbit 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_skin.rotateX;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_skin.rotateX;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateX;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_skin.rotateX;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_skin.rotateX;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateX;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_1_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_1_skin.rotateX 14.97313898;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_1_skin.rotateX;
selectKey -in 1 -at rotateX r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbSpread -10;
setAttr r_thumb_1_skin.rotateX 6.181270089;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_1_skin.rotateX;

setAttr r_fingers_anim.thumbSpread 0;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_1_skin.rotateX;

setAttr r_fingers_anim.thumbSpread 10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbSpread r_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateX;
setAttr r_fingers_anim.thumbSpread 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_skin.rotateX;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_skin.rotateX;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateX;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_skin.rotateX;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_skin.rotateX;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateX;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.spread -10;
setAttr r_thumb_1_skin.rotateX 6.181270089;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_1_skin.rotateX;

setAttr r_thumb_anim.spread 0;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_1_skin.rotateX;

setAttr r_thumb_anim.spread 10;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.spread r_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateX;
setAttr r_thumb_anim.spread 0 ;


setAttr r_thumb_anim.twist -10;
setAttr r_thumb_1_skin.rotateX 60;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.twist r_thumb_1_skin.rotateX;

setAttr r_thumb_anim.twist 0;
setAttr r_thumb_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.twist r_thumb_1_skin.rotateX;

setAttr r_thumb_anim.twist 10;
setAttr r_thumb_1_skin.rotateX -60;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.twist r_thumb_1_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateX;
setAttr r_thumb_anim.twist 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_skin.rotateY;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_skin.rotateY;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateY;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_skin.rotateY;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_skin.rotateY;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateY;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_1_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_1_skin.rotateY;
selectKey -in 1 -at rotateY r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbSpread -10;
setAttr r_thumb_1_skin.rotateY 53.40587414;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_1_skin.rotateY;

setAttr r_fingers_anim.thumbSpread 0;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_1_skin.rotateY;

setAttr r_fingers_anim.thumbSpread 10;
setAttr r_thumb_1_skin.rotateY -43.65116151;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbSpread r_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateY;
setAttr r_fingers_anim.thumbSpread 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_skin.rotateY;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_skin.rotateY;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateY;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_skin.rotateY;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_skin.rotateY;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateY;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.spread -10;
setAttr r_thumb_1_skin.rotateY 53.40587414;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_1_skin.rotateY;

setAttr r_thumb_anim.spread 0;
setAttr r_thumb_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_1_skin.rotateY;

setAttr r_thumb_anim.spread 10;
setAttr r_thumb_1_skin.rotateY -43.65116151;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.spread r_thumb_1_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateY;
setAttr r_thumb_anim.spread 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_1_skin.rotateZ 73.33178069;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_skin.rotateZ;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_1_skin.rotateZ;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_1_skin.rotateZ -69.86465637;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateZ;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_1_skin.rotateZ -10.36760247;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_skin.rotateZ;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_skin.rotateZ;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_1_skin.rotateZ 41.18425035;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateZ;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_1_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_1_skin.rotateZ -99.75624245;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbSpread -10;
setAttr r_thumb_1_skin.rotateZ -10.0196882;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_1_skin.rotateZ;

setAttr r_fingers_anim.thumbSpread 0;
setAttr r_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_1_skin.rotateZ;

setAttr r_fingers_anim.thumbSpread 10;
setAttr r_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbSpread r_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateZ;
setAttr r_fingers_anim.thumbSpread 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_1_skin.rotateZ 73.33178069;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_skin.rotateZ;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_1_skin.rotateZ;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_1_skin.rotateZ -69.86465637;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateZ;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_1_skin.rotateZ -10.36760247;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_skin.rotateZ;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_1_skin.rotateZ;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_1_skin.rotateZ 41.18425035;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateZ;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.bend_2 -10000;
setAttr r_thumb_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.bend_2 r_thumb_1_skin.rotateZ;

setAttr r_thumb_anim.bend_2 10000;
setAttr r_thumb_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.bend_2 r_thumb_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateZ;
setAttr r_thumb_anim.bend_2 0 ;


setAttr r_thumb_anim.spread -10;
setAttr r_thumb_1_skin.rotateZ -10.0196882;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_1_skin.rotateZ;

setAttr r_thumb_anim.spread 0;
setAttr r_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_1_skin.rotateZ;

setAttr r_thumb_anim.spread 10;
setAttr r_thumb_1_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.spread r_thumb_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_1_skin;
setInfinity -poi linear r_thumb_1_skin.rotateZ;
setAttr r_thumb_anim.spread 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_2_skin.rotateX;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_2_skin.rotateX;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateX;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_2_skin.rotateX;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_2_skin.rotateX;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateX;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_2_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_2_skin.rotateX;
selectKey -in 1 -at rotateX r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbSpread -10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_2_skin.rotateX;

setAttr r_fingers_anim.thumbSpread 0;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_2_skin.rotateX;

setAttr r_fingers_anim.thumbSpread 10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbSpread r_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateX;
setAttr r_fingers_anim.thumbSpread 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_2_skin.rotateX;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_2_skin.rotateX;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateX;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_2_skin.rotateX;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_2_skin.rotateX;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateX;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.spread -10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_2_skin.rotateX;

setAttr r_thumb_anim.spread 0;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_2_skin.rotateX;

setAttr r_thumb_anim.spread 10;
setAttr r_thumb_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.spread r_thumb_2_skin.rotateX;
selectKey -in 2 -at rotateX r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateX;
setAttr r_thumb_anim.spread 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_2_skin.rotateY;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_2_skin.rotateY;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateY;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_2_skin.rotateY;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_2_skin.rotateY;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateY;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_2_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_2_skin.rotateY;
selectKey -in 1 -at rotateY r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbSpread -10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_2_skin.rotateY;

setAttr r_fingers_anim.thumbSpread 0;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_2_skin.rotateY;

setAttr r_fingers_anim.thumbSpread 10;
setAttr r_thumb_2_skin.rotateY -0.8200437026;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbSpread r_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateY;
setAttr r_fingers_anim.thumbSpread 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_2_skin.rotateY;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_2_skin.rotateY;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateY;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_2_skin.rotateY;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_2_skin.rotateY;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateY;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.spread -10;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_2_skin.rotateY;

setAttr r_thumb_anim.spread 0;
setAttr r_thumb_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_2_skin.rotateY;

setAttr r_thumb_anim.spread 10;
setAttr r_thumb_2_skin.rotateY -0.8200437026;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.spread r_thumb_2_skin.rotateY;
selectKey -in 2 -at rotateY r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateY;
setAttr r_thumb_anim.spread 0 ;


setAttr r_fingers_anim.thumbCurl -10;
setAttr r_thumb_2_skin.rotateZ 29.82750794;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_2_skin.rotateZ;

setAttr r_fingers_anim.thumbCurl 0;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbCurl r_thumb_2_skin.rotateZ;

setAttr r_fingers_anim.thumbCurl 10;
setAttr r_thumb_2_skin.rotateZ -62.02574507;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbCurl r_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateZ;
setAttr r_fingers_anim.thumbCurl 0 ;


setAttr r_fingers_anim.thumbScrunch -10;
setAttr r_thumb_2_skin.rotateZ 17.23237314;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_2_skin.rotateZ;

setAttr r_fingers_anim.thumbScrunch 0;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbScrunch r_thumb_2_skin.rotateZ;

setAttr r_fingers_anim.thumbScrunch 10;
setAttr r_thumb_2_skin.rotateZ -125.1179665;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbScrunch r_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateZ;
setAttr r_fingers_anim.thumbScrunch 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_thumb_2_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_thumb_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.thumbSpread -10;
setAttr r_thumb_2_skin.rotateZ -3.604679367;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_2_skin.rotateZ;

setAttr r_fingers_anim.thumbSpread 0;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.thumbSpread r_thumb_2_skin.rotateZ;

setAttr r_fingers_anim.thumbSpread 10;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.thumbSpread r_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateZ;
setAttr r_fingers_anim.thumbSpread 0 ;


setAttr r_thumb_anim.curl -10;
setAttr r_thumb_2_skin.rotateZ 29.82750794;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_2_skin.rotateZ;

setAttr r_thumb_anim.curl 0;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.curl r_thumb_2_skin.rotateZ;

setAttr r_thumb_anim.curl 10;
setAttr r_thumb_2_skin.rotateZ -62.02574507;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.curl r_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateZ;
setAttr r_thumb_anim.curl 0 ;


setAttr r_thumb_anim.scrunch -10;
setAttr r_thumb_2_skin.rotateZ 17.23237314;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_2_skin.rotateZ;

setAttr r_thumb_anim.scrunch 0;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.scrunch r_thumb_2_skin.rotateZ;

setAttr r_thumb_anim.scrunch 10;
setAttr r_thumb_2_skin.rotateZ -125.1179665;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.scrunch r_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateZ;
setAttr r_thumb_anim.scrunch 0 ;


setAttr r_thumb_anim.bend_3 -10000;
setAttr r_thumb_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.bend_3 r_thumb_2_skin.rotateZ;

setAttr r_thumb_anim.bend_3 10000;
setAttr r_thumb_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.bend_3 r_thumb_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateZ;
setAttr r_thumb_anim.bend_3 0 ;


setAttr r_thumb_anim.spread -10;
setAttr r_thumb_2_skin.rotateZ -3.604679367;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_2_skin.rotateZ;

setAttr r_thumb_anim.spread 0;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_thumb_anim.spread r_thumb_2_skin.rotateZ;

setAttr r_thumb_anim.spread 10;
setAttr r_thumb_2_skin.rotateZ 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_thumb_anim.spread r_thumb_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_thumb_2_skin;
setInfinity -poi linear r_thumb_2_skin.rotateZ;
setAttr r_thumb_anim.spread 0 ;


if (`objExists r_fing_ring_base_dummy`)
{

setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_base_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_base_skin.rotateY 0.5503159555;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_base_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.spread -10;
setAttr r_fing_ring_base_skin.rotateY -6.715146913;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_ring_base_skin.rotateY;

setAttr r_fingers_anim.spread 0;
setAttr r_fing_ring_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_ring_base_skin.rotateY;

setAttr r_fingers_anim.spread 10;
setAttr r_fing_ring_base_skin.rotateY 6.43686341;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.spread r_fing_ring_base_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateY;
setAttr r_fingers_anim.spread 0 ;


setAttr r_ring_anim.spread -10;
setAttr r_fing_ring_base_skin.rotateY -6.715146913;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.spread r_fing_ring_base_skin.rotateY;

setAttr r_ring_anim.spread 0;
setAttr r_fing_ring_base_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.spread r_fing_ring_base_skin.rotateY;

setAttr r_ring_anim.spread 10;
setAttr r_fing_ring_base_skin.rotateY 6.43686341;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.spread r_fing_ring_base_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateY;
setAttr r_ring_anim.spread 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_ring_base_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_ring_base_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_ring_base_skin.rotateZ -3.862950164;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_ring_base_skin.rotateZ -6.066798462;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_ring_base_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_ring_base_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_ring_base_skin.rotateZ 4.937821436;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_ring_base_skin.rotateZ -2.013306497;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_ring_base_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_ring_base_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_ring_base_skin.rotateZ -9.008548927;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_base_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_base_skin.rotateZ -21.82017768;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_ring_anim.curl -10;
setAttr r_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.curl r_fing_ring_base_skin.rotateZ;

setAttr r_ring_anim.curl 0;
setAttr r_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.curl r_fing_ring_base_skin.rotateZ;

setAttr r_ring_anim.curl 10;
setAttr r_fing_ring_base_skin.rotateZ -3.862950164;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.curl r_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateZ;
setAttr r_ring_anim.curl 0 ;


setAttr r_ring_anim.scrunch -10;
setAttr r_fing_ring_base_skin.rotateZ -6.066798462;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.scrunch r_fing_ring_base_skin.rotateZ;

setAttr r_ring_anim.scrunch 0;
setAttr r_fing_ring_base_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.scrunch r_fing_ring_base_skin.rotateZ;

setAttr r_ring_anim.scrunch 10;
setAttr r_fing_ring_base_skin.rotateZ 4.937821436;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.scrunch r_fing_ring_base_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateZ;
setAttr r_ring_anim.scrunch 0 ;


setAttr r_ring_anim.bend_1 -10000;
setAttr r_fing_ring_base_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.bend_1 r_fing_ring_base_skin.rotateZ;

setAttr r_ring_anim.bend_1 10000;
setAttr r_fing_ring_base_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.bend_1 r_fing_ring_base_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateZ;
setAttr r_ring_anim.bend_1 0 ;



setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_base_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_base_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_base_skin.rotateX -26.17435115;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_base_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_ring_base_skin;
setInfinity -poi linear r_fing_ring_base_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;




setAttr r_fingers_anim.curl -10;
setAttr r_fing_ring_1_skin.rotateZ 73.32639952;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_ring_1_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_ring_1_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_ring_1_skin.rotateZ -96.99693582;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_ring_1_skin.rotateZ -8.83491194;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_ring_1_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_ring_1_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_ring_1_skin.rotateZ 62.38007767;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_ring_1_skin.rotateZ -12.4269624;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_ring_1_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_ring_1_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_ring_1_skin.rotateZ -54.33575059;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_1_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_1_skin.rotateZ -122.7776808;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_ring_anim.curl -10;
setAttr r_fing_ring_1_skin.rotateZ 73.32639952;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.curl r_fing_ring_1_skin.rotateZ;

setAttr r_ring_anim.curl 0;
setAttr r_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.curl r_fing_ring_1_skin.rotateZ;

setAttr r_ring_anim.curl 10;
setAttr r_fing_ring_1_skin.rotateZ -96.99693582;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.curl r_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateZ;
setAttr r_ring_anim.curl 0 ;


setAttr r_ring_anim.scrunch -10;
setAttr r_fing_ring_1_skin.rotateZ -8.83491194;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.scrunch r_fing_ring_1_skin.rotateZ;

setAttr r_ring_anim.scrunch 0;
setAttr r_fing_ring_1_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.scrunch r_fing_ring_1_skin.rotateZ;

setAttr r_ring_anim.scrunch 10;
setAttr r_fing_ring_1_skin.rotateZ 62.38007767;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.scrunch r_fing_ring_1_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateZ;
setAttr r_ring_anim.scrunch 0 ;


setAttr r_ring_anim.bend_2 -10000;
setAttr r_fing_ring_1_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.bend_2 r_fing_ring_1_skin.rotateZ;

setAttr r_ring_anim.bend_2 10000;
setAttr r_fing_ring_1_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.bend_2 r_fing_ring_1_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateZ;
setAttr r_ring_anim.bend_2 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_1_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_1_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_1_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.twist -10;
setAttr r_fing_ring_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.twist r_fing_ring_1_skin.rotateX;

setAttr r_fingers_anim.twist 0;
setAttr r_fing_ring_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.twist r_fing_ring_1_skin.rotateX;

setAttr r_fingers_anim.twist 10;
setAttr r_fing_ring_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.twist r_fing_ring_1_skin.rotateX;
selectKey -in 2 -at rotateX r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateX;
setAttr r_fingers_anim.twist 0 ;


setAttr r_ring_anim.twist -10;
setAttr r_fing_ring_1_skin.rotateX 30;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.twist r_fing_ring_1_skin.rotateX;

setAttr r_ring_anim.twist 0;
setAttr r_fing_ring_1_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.twist r_fing_ring_1_skin.rotateX;

setAttr r_ring_anim.twist 10;
setAttr r_fing_ring_1_skin.rotateX -30;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.twist r_fing_ring_1_skin.rotateX;
selectKey -in 2 -at rotateX r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateX;
setAttr r_ring_anim.twist 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_1_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_1_skin.rotateY 15.63936828;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_1_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.spread -10;
setAttr r_fing_ring_1_skin.rotateY -18.75286045;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_ring_1_skin.rotateY;

setAttr r_fingers_anim.spread 0;
setAttr r_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.spread r_fing_ring_1_skin.rotateY;

setAttr r_fingers_anim.spread 10;
setAttr r_fing_ring_1_skin.rotateY 15.23508417;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.spread r_fing_ring_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateY;
setAttr r_fingers_anim.spread 0 ;

setAttr r_fingers_anim.lean -10;
setAttr r_fing_ring_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_ring_1_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_ring_1_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_ring_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_ring_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_ring_anim.spread -10;
setAttr r_fing_ring_1_skin.rotateY -18.75286045;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.spread r_fing_ring_1_skin.rotateY;

setAttr r_ring_anim.spread 0;
setAttr r_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.spread r_fing_ring_1_skin.rotateY;

setAttr r_ring_anim.spread 10;
setAttr r_fing_ring_1_skin.rotateY 15.23508417;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.spread r_fing_ring_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateY;
setAttr r_ring_anim.spread 0 ;


setAttr r_ring_anim.lean -10;
setAttr r_fing_ring_1_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.lean r_fing_ring_1_skin.rotateY;

setAttr r_ring_anim.lean 0;
setAttr r_fing_ring_1_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.lean r_fing_ring_1_skin.rotateY;

setAttr r_ring_anim.lean 10;
setAttr r_fing_ring_1_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.lean r_fing_ring_1_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_1_skin;
setInfinity -poi linear r_fing_ring_1_skin.rotateY;
setAttr r_ring_anim.lean 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_ring_2_skin.rotateZ 18.77672402;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_ring_2_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_ring_2_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_ring_2_skin.rotateZ -86.45621096;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_ring_2_skin.rotateZ 5.353795415;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_ring_2_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_ring_2_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_ring_2_skin.rotateZ -105.2742772;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_ring_2_skin.rotateZ -16.04262404;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_ring_2_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_ring_2_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_ring_2_skin.rotateZ -32.77536134;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_2_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_2_skin.rotateZ -6.496048163;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_ring_anim.curl -10;
setAttr r_fing_ring_2_skin.rotateZ 18.77672402;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.curl r_fing_ring_2_skin.rotateZ;

setAttr r_ring_anim.curl 0;
setAttr r_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.curl r_fing_ring_2_skin.rotateZ;

setAttr r_ring_anim.curl 10;
setAttr r_fing_ring_2_skin.rotateZ -86.45621096;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.curl r_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateZ;
setAttr r_ring_anim.curl 0 ;


setAttr r_ring_anim.scrunch -10;
setAttr r_fing_ring_2_skin.rotateZ 5.353795415;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.scrunch r_fing_ring_2_skin.rotateZ;

setAttr r_ring_anim.scrunch 0;
setAttr r_fing_ring_2_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.scrunch r_fing_ring_2_skin.rotateZ;

setAttr r_ring_anim.scrunch 10;
setAttr r_fing_ring_2_skin.rotateZ -105.2742772;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.scrunch r_fing_ring_2_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateZ;
setAttr r_ring_anim.scrunch 0 ;


setAttr r_ring_anim.bend_3 -10000;
setAttr r_fing_ring_2_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.bend_3 r_fing_ring_2_skin.rotateZ;

setAttr r_ring_anim.bend_3 10000;
setAttr r_fing_ring_2_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.bend_3 r_fing_ring_2_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateZ;
setAttr r_ring_anim.bend_3 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_2_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_2_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_2_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_ring_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_ring_2_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_ring_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_ring_2_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_ring_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_ring_2_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_ring_anim.lean -10;
setAttr r_fing_ring_2_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.lean r_fing_ring_2_skin.rotateY;

setAttr r_ring_anim.lean 0;
setAttr r_fing_ring_2_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.lean r_fing_ring_2_skin.rotateY;

setAttr r_ring_anim.lean 10;
setAttr r_fing_ring_2_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.lean r_fing_ring_2_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateY;
setAttr r_ring_anim.lean 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_2_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_2_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_2_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_2_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_ring_2_skin;
setInfinity -poi linear r_fing_ring_2_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.curl -10;
setAttr r_fing_ring_3_skin.rotateZ 8.287590435;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_ring_3_skin.rotateZ;

setAttr r_fingers_anim.curl 0;
setAttr r_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.curl r_fing_ring_3_skin.rotateZ;

setAttr r_fingers_anim.curl 10;
setAttr r_fing_ring_3_skin.rotateZ -106.8633359;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.curl r_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateZ;
setAttr r_fingers_anim.curl 0 ;


setAttr r_fingers_anim.scrunch -10;
setAttr r_fing_ring_3_skin.rotateZ 14.72020741;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_ring_3_skin.rotateZ;

setAttr r_fingers_anim.scrunch 0;
setAttr r_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.scrunch r_fing_ring_3_skin.rotateZ;

setAttr r_fingers_anim.scrunch 10;
setAttr r_fing_ring_3_skin.rotateZ -80.8716872;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.scrunch r_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateZ;
setAttr r_fingers_anim.scrunch 0 ;


setAttr r_fingers_anim.relax -10;
setAttr r_fing_ring_3_skin.rotateZ -7.684617167;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_ring_3_skin.rotateZ;

setAttr r_fingers_anim.relax 0;
setAttr r_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.relax r_fing_ring_3_skin.rotateZ;

setAttr r_fingers_anim.relax 10;
setAttr r_fing_ring_3_skin.rotateZ -17.31530324;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.relax r_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateZ;
setAttr r_fingers_anim.relax 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_3_skin.rotateZ;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_3_skin.rotateZ -4.917483508;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_3_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateZ;
setAttr r_fingers_anim.cup 0 ;


setAttr r_ring_anim.curl -10;
setAttr r_fing_ring_3_skin.rotateZ 8.287590435;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.curl r_fing_ring_3_skin.rotateZ;

setAttr r_ring_anim.curl 0;
setAttr r_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.curl r_fing_ring_3_skin.rotateZ;

setAttr r_ring_anim.curl 10;
setAttr r_fing_ring_3_skin.rotateZ -106.8633359;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.curl r_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateZ;
setAttr r_ring_anim.curl 0 ;


setAttr r_ring_anim.scrunch -10;
setAttr r_fing_ring_3_skin.rotateZ 14.72020741;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.scrunch r_fing_ring_3_skin.rotateZ;

setAttr r_ring_anim.scrunch 0;
setAttr r_fing_ring_3_skin.rotateZ 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.scrunch r_fing_ring_3_skin.rotateZ;

setAttr r_ring_anim.scrunch 10;
setAttr r_fing_ring_3_skin.rotateZ -80.8716872;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.scrunch r_fing_ring_3_skin.rotateZ;
selectKey -in 2 -at rotateZ r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateZ;
setAttr r_ring_anim.scrunch 0 ;


setAttr r_ring_anim.bend_4 -10000;
setAttr r_fing_ring_3_skin.rotateZ 10000;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.bend_4 r_fing_ring_3_skin.rotateZ;

setAttr r_ring_anim.bend_4 10000;
setAttr r_fing_ring_3_skin.rotateZ -10000;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.bend_4 r_fing_ring_3_skin.rotateZ;
selectKey -in 1 -at rotateZ r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateZ;
setAttr r_ring_anim.bend_4 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_3_skin.rotateY;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_3_skin.rotateY 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_3_skin.rotateY;
selectKey -in 1 -at rotateY r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateY;
setAttr r_fingers_anim.cup 0 ;


setAttr r_fingers_anim.lean -10;
setAttr r_fing_ring_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_ring_3_skin.rotateY;

setAttr r_fingers_anim.lean 0;
setAttr r_fing_ring_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.lean r_fing_ring_3_skin.rotateY;

setAttr r_fingers_anim.lean 10;
setAttr r_fing_ring_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.lean r_fing_ring_3_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateY;
setAttr r_fingers_anim.lean 0 ;


setAttr r_ring_anim.lean -10;
setAttr r_fing_ring_3_skin.rotateY -17;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.lean r_fing_ring_3_skin.rotateY;

setAttr r_ring_anim.lean 0;
setAttr r_fing_ring_3_skin.rotateY 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_ring_anim.lean r_fing_ring_3_skin.rotateY;

setAttr r_ring_anim.lean 10;
setAttr r_fing_ring_3_skin.rotateY 17.33560999;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_ring_anim.lean r_fing_ring_3_skin.rotateY;
selectKey -in 2 -at rotateY r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateY;
setAttr r_ring_anim.lean 0 ;


setAttr r_fingers_anim.cup 0;
setAttr r_fing_ring_3_skin.rotateX 0;
setDrivenKeyframe -itt linear -ott linear -currentDriver r_fingers_anim.cup r_fing_ring_3_skin.rotateX;

setAttr r_fingers_anim.cup 10;
setAttr r_fing_ring_3_skin.rotateX 0;
setDrivenKeyframe -itt spline -ott spline -currentDriver r_fingers_anim.cup r_fing_ring_3_skin.rotateX;
selectKey -in 1 -at rotateX r_fing_ring_3_skin;
setInfinity -poi linear r_fing_ring_3_skin.rotateX;
setAttr r_fingers_anim.cup 0 ;


select -cl;
selectKey -add -k -f -10 animCurveUA409 ;
selectKey -add -k -f -10 animCurveUA410 ;
selectKey -add -k -f -10 r_fing_ring_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA411 ;
selectKey -add -k -f -10 animCurveUA412 ;
selectKey -add -k -f -10 animCurveUA414 ;
selectKey -add -k -f -10 animCurveUA415 ;
selectKey -add -k -f -10 r_fing_ring_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA417 ;
selectKey -add -k -f -10 animCurveUA418 ;
selectKey -add -k -f -10 animCurveUA420 ;
selectKey -add -k -f -10 animCurveUA421 ;
selectKey -add -k -f -10 animCurveUA423 ;
selectKey -add -k -f -10 animCurveUA424 ;
selectKey -add -k -f -10 animCurveUA425 ;
selectKey -add -k -f -10 animCurveUA426 ;
selectKey -add -k -f -10 animCurveUA427 ;
selectKey -add -k -f -10 animCurveUA428 ;
selectKey -add -k -f -10 r_fing_ring_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA429 ;
selectKey -add -k -f -10 animCurveUA430 ;
selectKey -add -k -f -10 animCurveUA432 ;
selectKey -add -k -f -10 animCurveUA433 ;
selectKey -add -k -f -10 animCurveUA435 ;
selectKey -add -k -f -10 animCurveUA436 ;
selectKey -add -k -f -10 r_fing_ring_3_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA437 ;
selectKey -add -k -f -10 animCurveUA438 ;
selectKey -add -k -f -10 animCurveUA440 ;
selectKey -add -k -f -10 animCurveUA441 ;
selectKey -add -k -f -10 animCurveUA443 ;
selectKey -add -k -f -10 animCurveUA444 ;

keyTangent -itt spline -ott spline;
setInfinity -pri linear;
}


select -r r_hand_base_skin ;
select -hi;
selectKey -clear ;
selectKey -add -k -f 10 r_thumb_base_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA297 ;
selectKey -add -k -f 10 animCurveUA298 ;
selectKey -add -k -f 10 animCurveUA299 ;
selectKey -add -k -f 10 animCurveUA300 ;
selectKey -add -k -f 10 animCurveUA301 ;
selectKey -add -k -f 10 animCurveUA302 ;
selectKey -add -k -f 10 animCurveUA303 ;
selectKey -add -k -f 10 r_thumb_base_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA304 ;
selectKey -add -k -f 10 animCurveUA305 ;
selectKey -add -k -f 10 animCurveUA306 ;
selectKey -add -k -f 10 animCurveUA307 ;
selectKey -add -k -f 10 animCurveUA308 ;
selectKey -add -k -f 10 animCurveUA309 ;
selectKey -add -k -f 10 animCurveUA310 ;
selectKey -add -k -f 10 r_thumb_base_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA311 ;
selectKey -add -k -f 10 animCurveUA312 ;
selectKey -add -k -f 10 animCurveUA313 ;
selectKey -add -k -f 10 animCurveUA314 ;
selectKey -add -k -f 10 animCurveUA315 ;
selectKey -add -k -f 10 animCurveUA316 ;
selectKey -add -k -f 10 animCurveUA318 ;
selectKey -add -k -f 10 r_thumb_1_twist_rotateX ;
selectKey -add -k -f 10 animCurveUA319 ;
selectKey -add -k -f 10 animCurveUA320 ;
selectKey -add -k -f 10 animCurveUA321 ;
selectKey -add -k -f 10 animCurveUA322 ;
selectKey -add -k -f 10 animCurveUA323 ;
selectKey -add -k -f 10 r_thumb_1_twist_rotateY ;
selectKey -add -k -f 10 animCurveUA324 ;
selectKey -add -k -f 10 animCurveUA325 ;
selectKey -add -k -f 10 animCurveUA326 ;
selectKey -add -k -f 10 animCurveUA327 ;
selectKey -add -k -f 10 animCurveUA328 ;
selectKey -add -k -f 10 r_thumb_1_twist_rotateZ ;
selectKey -add -k -f 10 animCurveUA329 ;
selectKey -add -k -f 10 animCurveUA330 ;
selectKey -add -k -f 10 animCurveUA331 ;
selectKey -add -k -f 10 animCurveUA332 ;
selectKey -add -k -f 10 animCurveUA333 ;
selectKey -add -k -f 10 r_thumb_1_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA334 ;
selectKey -add -k -f 10 animCurveUA335 ;
selectKey -add -k -f 10 animCurveUA336 ;
selectKey -add -k -f 10 animCurveUA337 ;
selectKey -add -k -f 10 animCurveUA338 ;
selectKey -add -k -f 10 animCurveUA339 ;
selectKey -add -k -f 10 animCurveUA340 ;
selectKey -add -k -f 10 r_thumb_1_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA341 ;
selectKey -add -k -f 10 animCurveUA342 ;
selectKey -add -k -f 10 animCurveUA343 ;
selectKey -add -k -f 10 animCurveUA344 ;
selectKey -add -k -f 10 animCurveUA345 ;
selectKey -add -k -f 10 animCurveUA346 ;
selectKey -add -k -f 10 r_thumb_1_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA347 ;
selectKey -add -k -f 10 animCurveUA348 ;
selectKey -add -k -f 10 animCurveUA349 ;
selectKey -add -k -f 10 animCurveUA350 ;
selectKey -add -k -f 10 animCurveUA351 ;
selectKey -add -k -f 10 animCurveUA353 ;
selectKey -add -k -f 10 r_thumb_2_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA354 ;
selectKey -add -k -f 10 animCurveUA355 ;
selectKey -add -k -f 10 animCurveUA356 ;
selectKey -add -k -f 10 animCurveUA357 ;
selectKey -add -k -f 10 animCurveUA358 ;
selectKey -add -k -f 10 animCurveUA359 ;
selectKey -add -k -f 10 r_thumb_2_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA360 ;
selectKey -add -k -f 10 animCurveUA361 ;
selectKey -add -k -f 10 animCurveUA362 ;
selectKey -add -k -f 10 animCurveUA363 ;
selectKey -add -k -f 10 animCurveUA364 ;
selectKey -add -k -f 10 animCurveUA365 ;
selectKey -add -k -f 10 r_thumb_2_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA366 ;
selectKey -add -k -f 10 animCurveUA367 ;
selectKey -add -k -f 10 animCurveUA368 ;
selectKey -add -k -f 10 animCurveUA369 ;
selectKey -add -k -f 10 animCurveUA370 ;
selectKey -add -k -f 10 animCurveUA372 ;
selectKey -add -k -f 10 r_fing_index_base_skin_rotateX ;
selectKey -add -k -f 10 r_fing_index_base_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA215 ;
selectKey -add -k -f 10 animCurveUA216 ;
selectKey -add -k -f 10 animCurveUA217 ;
selectKey -add -k -f 10 animCurveUA218 ;
selectKey -add -k -f 10 animCurveUA219 ;
selectKey -add -k -f 10 r_fing_index_base_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA221 ;
selectKey -add -k -f 10 animCurveUA222 ;
selectKey -add -k -f 10 r_fing_index_1_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA187 ;
selectKey -add -k -f 10 animCurveUA188 ;
selectKey -add -k -f 10 animCurveUA189 ;
selectKey -add -k -f 10 animCurveUA190 ;
selectKey -add -k -f 10 animCurveUA191 ;
selectKey -add -k -f 10 r_fing_index_1_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA193 ;
selectKey -add -k -f 10 animCurveUA194 ;
selectKey -add -k -f 10 r_fing_index_1_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA195 ;
selectKey -add -k -f 10 animCurveUA196 ;
selectKey -add -k -f 10 animCurveUA197 ;
selectKey -add -k -f 10 animCurveUA198 ;
selectKey -add -k -f 10 r_fing_index_2_skin_rotateX ;
selectKey -add -k -f 10 r_fing_index_2_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA199 ;
selectKey -add -k -f 10 animCurveUA200 ;
selectKey -add -k -f 10 animCurveUA201 ;
selectKey -add -k -f 10 animCurveUA202 ;
selectKey -add -k -f 10 animCurveUA203 ;
selectKey -add -k -f 10 r_fing_index_2_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA205 ;
selectKey -add -k -f 10 animCurveUA206 ;
selectKey -add -k -f 10 r_fing_index_3_skin_rotateX ;
selectKey -add -k -f 10 r_fing_index_3_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA207 ;
selectKey -add -k -f 10 animCurveUA208 ;
selectKey -add -k -f 10 animCurveUA209 ;
selectKey -add -k -f 10 animCurveUA210 ;
selectKey -add -k -f 10 animCurveUA211 ;
selectKey -add -k -f 10 r_fing_index_3_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA213 ;
selectKey -add -k -f 10 animCurveUA214 ;
selectKey -add -k -f 10 r_fing_middle_base_skin_rotateX ;
selectKey -add -k -f 10 r_fing_middle_base_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA223 ;
selectKey -add -k -f 10 animCurveUA224 ;
selectKey -add -k -f 10 animCurveUA225 ;
selectKey -add -k -f 10 animCurveUA226 ;
selectKey -add -k -f 10 animCurveUA227 ;
selectKey -add -k -f 10 r_fing_middle_base_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA230 ;
selectKey -add -k -f 10 animCurveUA231 ;
selectKey -add -k -f 10 r_fing_middle_1_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA240 ;
selectKey -add -k -f 10 animCurveUA241 ;
selectKey -add -k -f 10 animCurveUA242 ;
selectKey -add -k -f 10 animCurveUA243 ;
selectKey -add -k -f 10 animCurveUA244 ;
selectKey -add -k -f 10 r_fing_middle_1_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA246 ;
selectKey -add -k -f 10 animCurveUA247 ;
selectKey -add -k -f 10 r_fing_middle_1_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA249 ;
selectKey -add -k -f 10 animCurveUA250 ;
selectKey -add -k -f 10 animCurveUA251 ;
selectKey -add -k -f 10 animCurveUA252 ;
selectKey -add -k -f 10 r_fing_middle_2_skin_rotateX ;
selectKey -add -k -f 10 r_fing_middle_2_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA253 ;
selectKey -add -k -f 10 animCurveUA254 ;
selectKey -add -k -f 10 animCurveUA255 ;
selectKey -add -k -f 10 animCurveUA256 ;
selectKey -add -k -f 10 animCurveUA257 ;
selectKey -add -k -f 10 r_fing_middle_2_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA259 ;
selectKey -add -k -f 10 animCurveUA260 ;
selectKey -add -k -f 10 r_fing_middle_3_skin_rotateX ;
selectKey -add -k -f 10 r_fing_middle_3_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA261 ;
selectKey -add -k -f 10 animCurveUA262 ;
selectKey -add -k -f 10 animCurveUA263 ;
selectKey -add -k -f 10 animCurveUA264 ;
selectKey -add -k -f 10 animCurveUA265 ;
selectKey -add -k -f 10 r_fing_middle_3_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA267 ;
selectKey -add -k -f 10 animCurveUA268 ;
selectKey -add -k -f 10 r_fing_pinky_base_skin_rotateX ;
selectKey -add -k -f 10 r_fing_pinky_base_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA232 ;
selectKey -add -k -f 10 animCurveUA233 ;
selectKey -add -k -f 10 r_fing_pinky_base_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA234 ;
selectKey -add -k -f 10 animCurveUA235 ;
selectKey -add -k -f 10 animCurveUA236 ;
selectKey -add -k -f 10 animCurveUA237 ;
selectKey -add -k -f 10 animCurveUA238 ;
selectKey -add -k -f 10 r_fing_pinky_1_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA269 ;
selectKey -add -k -f 10 animCurveUA270 ;
selectKey -add -k -f 10 animCurveUA271 ;
selectKey -add -k -f 10 animCurveUA272 ;
selectKey -add -k -f 10 animCurveUA273 ;
selectKey -add -k -f 10 r_fing_pinky_1_skin_rotateX ;
selectKey -add -k -f 10 animCurveUA275 ;
selectKey -add -k -f 10 animCurveUA276 ;
selectKey -add -k -f 10 r_fing_pinky_1_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA277 ;
selectKey -add -k -f 10 animCurveUA278 ;
selectKey -add -k -f 10 animCurveUA279 ;
selectKey -add -k -f 10 animCurveUA280 ;
selectKey -add -k -f 10 r_fing_pinky_2_skin_rotateX ;
selectKey -add -k -f 10 r_fing_pinky_2_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA281 ;
selectKey -add -k -f 10 animCurveUA282 ;
selectKey -add -k -f 10 animCurveUA283 ;
selectKey -add -k -f 10 animCurveUA284 ;
selectKey -add -k -f 10 animCurveUA285 ;
selectKey -add -k -f 10 r_fing_pinky_2_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA287 ;
selectKey -add -k -f 10 animCurveUA288 ;
selectKey -add -k -f 10 r_fing_pinky_3_skin_rotateX ;
selectKey -add -k -f 10 r_fing_pinky_3_skin_rotateZ ;
selectKey -add -k -f 10 animCurveUA289 ;
selectKey -add -k -f 10 animCurveUA290 ;
selectKey -add -k -f 10 animCurveUA291 ;
selectKey -add -k -f 10 animCurveUA292 ;
selectKey -add -k -f 10 animCurveUA293 ;
selectKey -add -k -f 10 r_fing_pinky_3_skin_rotateY ;
selectKey -add -k -f 10 animCurveUA295 ;
selectKey -add -k -f 10 animCurveUA296 ;
setInfinity -poi linear;
selectKey -clear ;
selectKey -add -k -f -10 r_thumb_base_skin_rotateX ;
selectKey -add -k -f -10 animCurveUA297 ;
selectKey -add -k -f -10 animCurveUA299 ;
selectKey -add -k -f -10 animCurveUA300 ;
selectKey -add -k -f -10 animCurveUA301 ;
selectKey -add -k -f -10 animCurveUA302 ;
selectKey -add -k -f -10 animCurveUA303 ;
selectKey -add -k -f -10 r_thumb_base_skin_rotateY ;
selectKey -add -k -f -10 animCurveUA304 ;
selectKey -add -k -f -10 animCurveUA306 ;
selectKey -add -k -f -10 animCurveUA307 ;
selectKey -add -k -f -10 animCurveUA308 ;
selectKey -add -k -f -10 animCurveUA309 ;
selectKey -add -k -f -10 animCurveUA310 ;
selectKey -add -k -f -10 r_thumb_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA311 ;
selectKey -add -k -f -10 animCurveUA313 ;
selectKey -add -k -f -10 animCurveUA314 ;
selectKey -add -k -f -10 animCurveUA315 ;
selectKey -add -k -f -10 animCurveUA316 ;
selectKey -add -k -f -10 animCurveUA318 ;
selectKey -add -k -f -10 r_thumb_1_twist_rotateX ;
selectKey -add -k -f -10 animCurveUA319 ;
selectKey -add -k -f -10 animCurveUA321 ;
selectKey -add -k -f -10 animCurveUA322 ;
selectKey -add -k -f -10 animCurveUA323 ;
selectKey -add -k -f -10 r_thumb_1_twist_rotateY ;
selectKey -add -k -f -10 animCurveUA324 ;
selectKey -add -k -f -10 animCurveUA326 ;
selectKey -add -k -f -10 animCurveUA327 ;
selectKey -add -k -f -10 animCurveUA328 ;
selectKey -add -k -f -10 r_thumb_1_twist_rotateZ ;
selectKey -add -k -f -10 animCurveUA329 ;
selectKey -add -k -f -10 animCurveUA331 ;
selectKey -add -k -f -10 animCurveUA332 ;
selectKey -add -k -f -10 animCurveUA333 ;
selectKey -add -k -f -10 r_thumb_1_skin_rotateX ;
selectKey -add -k -f -10 animCurveUA334 ;
selectKey -add -k -f -10 animCurveUA336 ;
selectKey -add -k -f -10 animCurveUA337 ;
selectKey -add -k -f -10 animCurveUA338 ;
selectKey -add -k -f -10 animCurveUA339 ;
selectKey -add -k -f -10 animCurveUA340 ;
selectKey -add -k -f -10 r_thumb_1_skin_rotateY ;
selectKey -add -k -f -10 animCurveUA341 ;
selectKey -add -k -f -10 animCurveUA343 ;
selectKey -add -k -f -10 animCurveUA344 ;
selectKey -add -k -f -10 animCurveUA345 ;
selectKey -add -k -f -10 animCurveUA346 ;
selectKey -add -k -f -10 r_thumb_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA347 ;
selectKey -add -k -f -10 animCurveUA349 ;
selectKey -add -k -f -10 animCurveUA350 ;
selectKey -add -k -f -10 animCurveUA351 ;
selectKey -add -k -f -10 animCurveUA353 ;
selectKey -add -k -f -10 r_thumb_2_skin_rotateX ;
selectKey -add -k -f -10 animCurveUA354 ;
selectKey -add -k -f -10 animCurveUA356 ;
selectKey -add -k -f -10 animCurveUA357 ;
selectKey -add -k -f -10 animCurveUA358 ;
selectKey -add -k -f -10 animCurveUA359 ;
selectKey -add -k -f -10 r_thumb_2_skin_rotateY ;
selectKey -add -k -f -10 animCurveUA360 ;
selectKey -add -k -f -10 animCurveUA362 ;
selectKey -add -k -f -10 animCurveUA363 ;
selectKey -add -k -f -10 animCurveUA364 ;
selectKey -add -k -f -10 animCurveUA365 ;
selectKey -add -k -f -10 r_thumb_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA366 ;
selectKey -add -k -f -10 animCurveUA368 ;
selectKey -add -k -f -10 animCurveUA369 ;
selectKey -add -k -f -10 animCurveUA370 ;
selectKey -add -k -f -10 animCurveUA372 ;
selectKey -add -k -f -10 r_fing_index_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA215 ;
selectKey -add -k -f -10 animCurveUA216 ;
selectKey -add -k -f -10 animCurveUA218 ;
selectKey -add -k -f -10 animCurveUA219 ;
selectKey -add -k -f -10 animCurveUA221 ;
selectKey -add -k -f -10 animCurveUA222 ;
selectKey -add -k -f -10 r_fing_index_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA187 ;
selectKey -add -k -f -10 animCurveUA188 ;
selectKey -add -k -f -10 animCurveUA190 ;
selectKey -add -k -f -10 animCurveUA191 ;
selectKey -add -k -f -10 animCurveUA193 ;
selectKey -add -k -f -10 animCurveUA194 ;
selectKey -add -k -f -10 animCurveUA195 ;
selectKey -add -k -f -10 animCurveUA196 ;
selectKey -add -k -f -10 animCurveUA197 ;
selectKey -add -k -f -10 animCurveUA198 ;
selectKey -add -k -f -10 r_fing_index_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA199 ;
selectKey -add -k -f -10 animCurveUA200 ;
selectKey -add -k -f -10 animCurveUA202 ;
selectKey -add -k -f -10 animCurveUA203 ;
selectKey -add -k -f -10 animCurveUA205 ;
selectKey -add -k -f -10 animCurveUA206 ;
selectKey -add -k -f -10 r_fing_index_3_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA207 ;
selectKey -add -k -f -10 animCurveUA208 ;
selectKey -add -k -f -10 animCurveUA210 ;
selectKey -add -k -f -10 animCurveUA211 ;
selectKey -add -k -f -10 animCurveUA213 ;
selectKey -add -k -f -10 animCurveUA214 ;
selectKey -add -k -f -10 r_fing_middle_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA223 ;
selectKey -add -k -f -10 animCurveUA224 ;
selectKey -add -k -f -10 animCurveUA226 ;
selectKey -add -k -f -10 animCurveUA227 ;
selectKey -add -k -f -10 animCurveUA230 ;
selectKey -add -k -f -10 animCurveUA231 ;
selectKey -add -k -f -10 r_fing_middle_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA240 ;
selectKey -add -k -f -10 animCurveUA241 ;
selectKey -add -k -f -10 animCurveUA243 ;
selectKey -add -k -f -10 animCurveUA244 ;
selectKey -add -k -f -10 animCurveUA246 ;
selectKey -add -k -f -10 animCurveUA247 ;
selectKey -add -k -f -10 animCurveUA249 ;
selectKey -add -k -f -10 animCurveUA250 ;
selectKey -add -k -f -10 animCurveUA251 ;
selectKey -add -k -f -10 animCurveUA252 ;
selectKey -add -k -f -10 r_fing_middle_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA253 ;
selectKey -add -k -f -10 animCurveUA254 ;
selectKey -add -k -f -10 animCurveUA256 ;
selectKey -add -k -f -10 animCurveUA257 ;
selectKey -add -k -f -10 animCurveUA259 ;
selectKey -add -k -f -10 animCurveUA260 ;
selectKey -add -k -f -10 r_fing_middle_3_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA261 ;
selectKey -add -k -f -10 animCurveUA262 ;
selectKey -add -k -f -10 animCurveUA264 ;
selectKey -add -k -f -10 animCurveUA265 ;
selectKey -add -k -f -10 animCurveUA267 ;
selectKey -add -k -f -10 animCurveUA268 ;
selectKey -add -k -f -10 animCurveUA232 ;
selectKey -add -k -f -10 animCurveUA233 ;
selectKey -add -k -f -10 r_fing_pinky_base_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA234 ;
selectKey -add -k -f -10 animCurveUA235 ;
selectKey -add -k -f -10 animCurveUA237 ;
selectKey -add -k -f -10 animCurveUA238 ;
selectKey -add -k -f -10 r_fing_pinky_1_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA269 ;
selectKey -add -k -f -10 animCurveUA270 ;
selectKey -add -k -f -10 animCurveUA272 ;
selectKey -add -k -f -10 animCurveUA273 ;
selectKey -add -k -f -10 animCurveUA275 ;
selectKey -add -k -f -10 animCurveUA276 ;
selectKey -add -k -f -10 animCurveUA277 ;
selectKey -add -k -f -10 animCurveUA278 ;
selectKey -add -k -f -10 animCurveUA279 ;
selectKey -add -k -f -10 animCurveUA280 ;
selectKey -add -k -f -10 r_fing_pinky_2_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA281 ;
selectKey -add -k -f -10 animCurveUA282 ;
selectKey -add -k -f -10 animCurveUA284 ;
selectKey -add -k -f -10 animCurveUA285 ;
selectKey -add -k -f -10 animCurveUA287 ;
selectKey -add -k -f -10 animCurveUA288 ;
selectKey -add -k -f -10 r_fing_pinky_3_skin_rotateZ ;
selectKey -add -k -f -10 animCurveUA289 ;
selectKey -add -k -f -10 animCurveUA290 ;
selectKey -add -k -f -10 animCurveUA292 ;
selectKey -add -k -f -10 animCurveUA293 ;
selectKey -add -k -f -10 animCurveUA295 ;
selectKey -add -k -f -10 animCurveUA296 ;
keyTangent -itt spline -ott spline;
setInfinity -pri linear;



}